### ISSUE TITLE
Not Working on MacOS Mojave?

### ISSUE THREAD

**Issue by faxotherapy** [freedomofpress/dangerzone#107]
Hi,
after putting the app im my App folder I clicked twice on the icon in the hope of opening the app. Unfortunately, nothing happens.

![FailedLaunched](https://user-images.githubusercontent.com/6538008/108987012-b4740980-768a-11eb-849a-30b22adb3672.gif)

**Comment by gmarmstrong** [comment]
Potentially related to #43? Though if so, it would have been fixed with version 0.1.1 by this date.

**Comment by faxotherapy** [comment]
Possibly, I'm on MacOS Mojave. Thx for your reply.

**Comment by apyrgio** [comment]
Closing this issue, as it seems to be resolved (and we never managed to reproduce it). Feel free to reopen it though, if it affects the latest Dangerzone version.
