### ISSUE TITLE
Unneeded dependency: macholib

### ISSUE THREAD

**Issue by Enchufa2** [freedomofpress/dangerzone#145]
Is `macholib` required? I was trying to package this for Fedora, and I was confused, because the build instructions do not include this library, but the poetry lock lists it.

**Comment by truthinhoney** [comment]
Yes, `macholib` is required.

**Comment by Enchufa2** [comment]
Sorry to insist, but are we sure? Because a grep shows that this is only referenced in `poetry.lock` and `pyproject.toml`, but nowhere else.

**Comment by truthinhoney** [comment]
I asked `https://fedoraproject.org/wiki/User:Ankursinha` and he told me that it _should_ be required since it is mentioned in `pyproject.toml`, but he also said to wait for upstream developer to give proper answer.

Honestly I barely know anything about packaging or programming so I am not certain that it is required lol.

Thank you for attempting to package this for Fedora! :)

**Comment by gmarmstrong** [comment]
I believe `macholib` is just an unused remnant from [when `pyobjc-core` (which depends on `macholib`) was added](https://github.com/freedomofpress/dangerzone/commit/810fa31a69c42faee4218caed2e03296214148db). `macholib` was automatically added to the `Pipfile.lock`, and it looks like it made its way into the `pyproject.toml` dependencies [when the switch was made](https://github.com/freedomofpress/dangerzone/commit/400b8d2b8312866170f2c7dfbff74087655fd1ae) from pipenv to poetry. The `pyobjc-core` dependency [was eventually removed](https://github.com/freedomofpress/dangerzone/commit/112291f82a38d09ec013b40dd4ab514517fabb53), but `macholib` remained. Removing it from the poetry environment now doesn't cause any problems, and I can even rebuild the container and macOS app on a Mac without `macholib`. The entry (if kept at all) should probably be something like:

```toml
[tool.poetry.dev-dependencies]
macholib = {version = "*", platform = "darwin", optional=true}
```

I'm not a maintainer, so take that with a grain of salt.

**Comment by gmarmstrong** [comment]
Ah, `macholib` is also a dependency of `pyinstaller`, which is only needed for `platform = "darwin"` (macOS). Found that out through `poetry show --tree`. Still, no need to package it.
