### ISSUE TITLE
Error compressing single-page, small-sized, high-resolution PDF

### ISSUE THREAD

**Issue by sycam0r-e** [freedomofpress/dangerzone#146]
Host OS: macOS 10.14.6
Docker Desktop: Version 4.4.2 (73305)
Danger Zone: Version 0.3.1

Problem:
I try to convert a one-sided PDF that has a size of 922KB and a resolution of 6048 × 3024. It contains a lot of pictures and graphs. The whole process works until Dangerzone "Compresses PDF" and throws the following error message: "Error compressing PDF, ps2pdf timed out after 3 seconds". This happens independently of whether OCR or opening the safe PDF after converting are selected.

Expected behavior:
Dangerzone should successfully compress the PDF.

This issues is similar to #70. Maybe the fix could be, too, by increasing the timeout or calculate it based on the PDF's _resolution_?

Let me know if you need further information.

**Comment by gmarmstrong** [comment]
The file compression step has a different timeout value (3 seconds per page) than our default of 60 seconds (which itself has caused problems in #70, as you point out):

https://github.com/freedomofpress/dangerzone/blob/d8adb2e9cc1bee17ffe21a006cfc7878e4a13bc3/container/dangerzone.py#L487

Relaxing that would certainly help, and file size would be a good start. Ideally, we would have no timeout at all as long as we can see that the process is making progress. From that, we could even calculate an ETA on the expected duration. If `ps2pdf` (which we use for PDF compression) doesn't have that capability, then it also being a culprit in #158 would make me want to reconsider using it as a compression tool.

**Comment by apyrgio** [comment]
We will bump the timeout in the 0.4.0 release (not yet released). Let's keep this issue open for a little while, so that we can see if an increased timeout helps. Please comment here once you have 0.4.0 installed and this bug still affects you. Else, we can close this issue.

Note that increasing the timeout won't solve the underlying issue, but it will make it very rare, which is a good first step.

**Comment by flippflapp** [comment]
Thanks, this sounds reasonable.

**Comment by apyrgio** [comment]
Timeout issues have been resolved in recent Dangerzone releases. Closing this issue, but feel free to re-open it if you still have a problem.
