### ISSUE TITLE
Windows installer: add option to change installation directory

### ISSUE THREAD

**Issue by paero123** [freedomofpress/dangerzone#148]
An msi package installation wants drive c:/ to install (unfortunately not enough disc space) and does not allow to change it to d:/ drive (disc space available). Is it a bug?

**Comment by FelixdelasPozas** [comment]
I did it like this:
- Open a terminal/cmd
- Go to the directory where dangezone msi file is.
- execute ```msiexec /i "Dangerzone-0.3.1.msi" INSTALLDIR="D:\Program Files (x86)\Dangerzone"```
