### ISSUE TITLE
Fedora 35 exception: no package metadata

### ISSUE THREAD

**Issue by raffaem** [freedomofpress/dangerzone#156]
I have installed dangerzone with:
```
curl -s https://packagecloud.io/install/repositories/firstlookmedia/code/script.rpm.sh | sudo bash
sudo dnf install -y dangerzone
```

But the software throws an  exception:

```
$ dangerzone
Traceback (most recent call last):
  File "/usr/bin/dangerzone", line 33, in <module>
    sys.exit(load_entry_point('dangerzone==0.3.1', 'console_scripts', 'dangerzone')())
  File "/usr/bin/dangerzone", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 957, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for dangerzone
```

**Comment by deeplow** [comment]
I have followed the install instructions and it lead me to the same issue on a fedora-35 VM running under Qubes.

However, when I build the package from source on the v0.3.1 tag (which should be the same version) it works fine.

Will investigate.

**Comment by prdwyer** [comment]
same issue on fedora 37 with the following error

`~  dangerzone                    
Traceback (most recent call last):
  File "/usr/lib64/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/dangerzone", line 33, in <module>
    sys.exit(load_entry_point('dangerzone==0.4.0', 'console_scripts', 'dangerzone')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/dangerzone", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for dangerzone
`

**Comment by apyrgio** [comment]
Thanks a lot for the report @prdwyer, and especially for the traceback. It seems that another user (https://github.com/freedomofpress/dangerzone/issues/307) has stumbled on this issue, so we looked into it.

Turns out that our CI runners were erroneously building RPM packages for Fedora 37 in Fedora 36. This means that the produced RPM package installs Dangerzone for Python 3.10, instead of 3.11, which is the root cause for the traceback you see.

We plan to upload a new Fedora 37 package in our repo, which you should be able to install with regular `dnf` commands. We'll ping you really soon about this.

**Comment by apyrgio** [comment]
Update: We have published a new package (`dangerzone-0.4.0-2`) in the Fedora 37 repos, and **only there**. We have tested that this new package fixes the error you have encountered.

You can install this package either with `dnf update`, or `dnf install dangerzone` specifically.

I'll close this issue, since it seems to be resolved. If this is not the case, please send us an update. Thanks again for your report!

**Comment by prdwyer** [comment]
i dont see the package on the repos yet but thanks for the action on this. i assume itll trickle in over time

**Comment by apyrgio** [comment]
Hm, let's not leave this to chance, until we're sure we've resolved it. Running the following command on a fresh Fedora 37 system, I see the following:

```
# dnf --showduplicates list dangerzone
Last metadata expiration check: 0:00:20 ago on Thu Jan 26 07:42:40 2023.
Available Packages
dangerzone.noarch                                                                      0.4.0-1                                                                       firstlookmedia_code       
dangerzone.src                                                                         0.4.0-1                                                                       firstlookmedia_code-source
dangerzone.noarch                                                                      0.4.0-2                                                                       firstlookmedia_code       
dangerzone.src                                                                         0.4.0-2                                                                       firstlookmedia_code-source
```

Do you see the same?

**Comment by prdwyer** [comment]
im seeing this:

```
sudo dnf --showduplicates --refresh list dangerzone         
.....
.....

Installed Packages
dangerzone.noarch                    0.4.0-1                     @firstlookmedia_code      
Available Packages
dangerzone.noarch                    0.3.2-1                     firstlookmedia_code       
dangerzone.src                       0.3.2-1                     firstlookmedia_code-source
dangerzone.noarch                    0.4.0-1                     firstlookmedia_code       
dangerzone.src                       0.4.0-1                     firstlookmedia_code-source
```

**Comment by apyrgio** [comment]
Could it be that you had originally installed Fedora 35/36, and recently upgraded to Fedora 37? If so, then Dangerzone's RPM repo will point to the packages for the previous Fedora release, which explains why you don't receive updates.

Let's find out. This is what I see in a Fedora 37 system:

```
# cat /etc/yum.repos.d/firstlookmedia_code.repo 
[firstlookmedia_code]
name=firstlookmedia_code
baseurl=https://packagecloud.io/firstlookmedia/code/fedora/37/$basearch
repo_gpgcheck=0
gpgcheck=0
enabled=1
gpgkey=https://packagecloud.io/firstlookmedia/code/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300

[firstlookmedia_code-source]
name=firstlookmedia_code-source
baseurl=https://packagecloud.io/firstlookmedia/code/fedora/37/SRPMS
repo_gpgcheck=0
gpgcheck=0
enabled=1
gpgkey=https://packagecloud.io/firstlookmedia/code/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300
```

If you see something similar, but with a lower Fedora version, can you please update this file, either manually or via the script in our [installation instructions](https://github.com/freedomofpress/dangerzone/blob/main/INSTALL.md#fedora)?

**Comment by raffaem** [comment]
I don't use this anymore

**Comment by prdwyer** [comment]
this fixed it. Thank you so much for your help i know you arent responsible for doing OS support like this!
