### ISSUE TITLE
macOS dev build instructions are incomplete

### ISSUE THREAD

**Issue by huertanix** [freedomofpress/dangerzone#159]
When going through the steps for building a dev environment in macOS here: https://github.com/freedomofpress/dangerzone/blob/main/BUILD.md, once you reach `poetry install`, that command does not run, and returns `zsh: command not found: poetry` possible due to a missing step where either a shell needs to be restarted, z shell dotfile needs to be updated, or possibly something else along those lines.

**Comment by deeplow** [comment]
I've encountered the same issue. The solution I found at the time was running using the full poetry path, which is in the python bin directory. I don't have access to a mac at the moment but it was something along the lines of `/Library/python/...`. You can run `which python` to see the python path.

When I get access to a Mac again, I'll check back and post the full thing.

Then I'll see if I find a way to add poetry to the path so this doesn't happen again. If that doesn't work, update the instructions to run poetry from the absolute path.

**Comment by deeplow** [comment]
This should have been solved with https://github.com/freedomofpress/dangerzone/pull/198/files, So I'll close it for now.

Feel free to re-open with these updated instructions you still can't get poetry to run.
