### ISSUE TITLE
Why is it compulsory to be online in order to use dangerzone?

### ISSUE THREAD

**Issue by est61** [freedomofpress/dangerzone#160]
I have installed via Ubuntu instructions, and when i run Dangerzone and try to convert a pdf, if im offline it will error out and wont continue.
Multiple times i have tried this, is there a setting to disable online update checking?

I find it very strange and makes one think why must it connect to the internet for updates each and every time for it to convert a pdf?

I dont like docker for many reasons, and i dont find it a safe option either. Why can't Dangerzone be updated at will, if the user chooses to, via apt-get via your repo?

Everything with Dangerzone works well, except this, it feels very wrong, like its doing whatever it wants and forces my to go online, otherwise it wont work.

If there is indeed a way to stop Dangerzone from updating via docker, and i have failed to see it, please tell me how.

**Comment by micahflee** [comment]
Since Dangerzone 0.3, when we started shipping the container image directly with the linux package, it should no longer require you to be online. Before it required internet just to download the latest container image and to check the container image for updates.

What version of Dangerzone are you running? Can you show more information, like what error you're getting if you're offline?

**Comment by est61** [comment]
Been having it on Ubuntu 18.04:

```
dangerzone:
  Installed: 0.1.3-1
  Candidate: 0.1.3-1
  Version table:
 *** 0.1.3-1 500
        500 https://packagecloud.io/firstlookmedia/code/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     0.1.2-1 500
        500 https://packagecloud.io/firstlookmedia/code/ubuntu bionic/main amd64 Packages
```

cat /etc/apt/sources.list.d/firstlookmedia_code.list
```
deb https://packagecloud.io/firstlookmedia/code/ubuntu/ bionic main
deb-src https://packagecloud.io/firstlookmedia/code/ubuntu/ bionic main
```


I tried updating, and it didn't find a new release.
Then i updated the lines to the correct ones from https://packagecloud.io/firstlookmedia/code/install#manual-deb
and still no new release.

Then I tried on Ubuntu 20.04 as well:

```
dangerzone:
  Installed: (none)
  Candidate: 0.2-1
  Version table:
     0.2-1 500
        500 https://packagecloud.io/firstlookmedia/code/ubuntu focal/main amd64 Packages
     0.1.5-1 500
        500 https://packagecloud.io/firstlookmedia/code/ubuntu focal/main amd64 Packages
     0.1.4-1 500
        500 https://packagecloud.io/firstlookmedia/code/ubuntu focal/main amd64 Packages
     0.1.3-1 500
        500 https://packagecloud.io/firstlookmedia/code/ubuntu focal/main amd64 Packages
```


incase you're wondering, i did add the key with:
`curl -fsSL https://packagecloud.io/firstlookmedia/code/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/firstlookmedia_code-archive-keyring.gpg`

Can you tell me why its not getting latest release in both distro versions?
