### ISSUE TITLE
Support building on M1 macs

### ISSUE THREAD

**Issue by deeplow** [freedomofpress/dangerzone#177]
The `shiboken2` package fails to install on m1s because it has no builds for ARM architectures on macbooks ([no available wheels](https://pypi.org/simple/shiboken2/)).

---

 When running `poetry install` on an m1 macbook:

![error_shiboken](https://user-images.githubusercontent.com/47065258/180788493-8a725a44-1ead-4d32-b6cc-5d022cdb9572.png)

_Originally posted by @deeplow in https://github.com/freedomofpress/dangerzone/issues/172#issuecomment-1194050403_

**Comment by deeplow** [comment]
Confirmed by @gmarmstrong in https://github.com/freedomofpress/dangerzone/pull/161#issuecomment-1205209190.

**Comment by deeplow** [comment]
To clarify, Dangerzone runs fine on m1 macs. What I can't seem to do is to setup the development environment due to dependency issues (shiboken).

**Comment by deeplow** [comment]
Until this this addressed, installing on M1 macs will involve activating rosetta (Apple's amd64 to arm emulation layer)

![image(3)](https://user-images.githubusercontent.com/47065258/204273386-0c22a308-547e-41eb-adcd-e220b1b36684.png)

I had not seen this before when setting up on an m1 mac but that was probably due to the machine being already provisioned with rosetta.

**Comment by deeplow** [comment]
Our current approach to may be :

```python
try: 
  Pyside2...
except ImportError:
  PySide6...
```

or maybe we should do with platform conditions.

On Poetry - find a way to have platform-specific dependencies - Add PySide6 for MacOS.

**Comment by apyrgio** [comment]
Update regarding the final implementation of this feature:

1. PySide6 does not have sufficient type checking stubs, so we can't use Mypy to check it (see #320). To circumvent this issue, we always perform type checking with the PySide2 stubs, since the API is compatible.
    * A problem with the existing PySide2 stubs is that they also bring PySide2 as a dependency. This means that in dev environments where we install PySide6 (currently Windows and MacOS), we would need to install PySide2 as well, which would potentially mask import problems. Worse, for MacOS M1 machines, this is not possible to do in the first place, since we can't install PySide2.
       
      A solution to this problem is to replace [PySide2-stubs](https://github.com/python-qt-tools/PySide2-stubs) with [types-PySide2](https://github.com/chadrik/types-PySide), which does not have this dependency, and has better Mypy stubs.
