### ISSUE TITLE
Add defense-in-depth: seccomp & apparmor

### ISSUE THREAD

**Issue by deeplow** [freedomofpress/dangerzone#182]
Consider adding defense-in-depth mechanisms limiting the scope of what a compromised dangerzone & associated programs can do on the system.

Strategies to consider:
  - apparmor
  - seccomp

Related:
  - https://github.com/freedomofpress/dangerzone/issues/52 - seccomp mentioned but not implemented

**Comment by deeplow** [comment]
This should be added only after setting up a set of automated tests both to help generate the profiles and to guarantee we caught most regular usage.

**Comment by eloquence** [comment]
Tentatively added to 0.4.0 milestone, but we'll need to decide initial scope (e.g., AppArmor only?).

**Comment by apyrgio** [comment]
Closing this issue in favor of #225 (seccomp) and #227 (AppArmor), which are part of the larger #221 (defense in depth) issue.
