### ISSUE TITLE
Support Ubuntu 22.04

### ISSUE THREAD

**Issue by haplo** [freedomofpress/dangerzone#199]
New Ubuntu LTS 22.04 has been out for a few months now, it would be great for Dangerzone to support it.

**Comment by deeplow** [comment]
It should run there. Have you followed [these instructions](https://github.com/freedomofpress/dangerzone/wiki/Installing-Dangerzone#ubuntu-debian)? It's one of the systems [that we're testing](https://app.circleci.com/pipelines/github/freedomofpress/dangerzone/404/workflows/a72b39a5-4592-4c00-a2c2-bbfd62a77e62/jobs/1586) so it should work in theory.

If it doesn't work, can you describe here what happens?

**Comment by haplo** [comment]
Might not be Ubuntu 22.04 related, but IPv6.

```
# apt update
[...]
Err:8 https://packagecloud.io/firstlookmedia/code/ubuntu jammy Release
  404  Not Found [IP: 2600:1f1c:2e5:6901:c538:2c09:65ea:d71d 443]
Reading package lists...
E: The repository 'https://packagecloud.io/firstlookmedia/code/ubuntu jammy Release' does not have a Release file.
```

**Comment by deeplow** [comment]
Hum. Actually, I think you're right. Even though we're building for it at the moment that was only a recent change. The current install instructions [still state older ubuntu releases](https://github.com/freedomofpress/dangerzone/wiki/Installing-Dangerzone). So it won't be available until the next release is published (which should be very soon ~1 more week or so).

For the time being I'd suggest you install [build from source](https://github.com/firstlookmedia/dangerzone/blob/master/BUILD.md) (if you're willing to do that) or wait a bit.

**Comment by haplo** [comment]
No rush from me, I already had dangerzone installed, I hit this issue when upgrading from Ubuntu 20.04 to 22.04.

If you ping me here when the new release is ready I would be happy to test it and report.

Thank you for your support!

**Comment by deeplow** [comment]
Perfect. Thank you @haplo

**Comment by haplo** [comment]
dangerzone installed today without no further change on my part. :+1: 

I'm closing this issue as fixed.
