### ISSUE TITLE
changed code signature in MacOS download 0.3.2

### ISSUE THREAD

**Issue by suschizu** [freedomofpress/dangerzone#201]
Hello @micahflee -  I just noticed that the code signature has changed:
`EXPECTED Micah Lee (N9B95FDWH4) but FOUND FIRST LOOK PRODUCTIONS, INC. (P24U45L8P5)`
can you confirm this? thanks

**Comment by micahflee** [comment]
Yes I can confirm the change in signing keys. And actually, it will likely change one more time in the near future, when Freedom of the Press Foundation takes over code signing. At that point it should stay the same.
