### ISSUE TITLE
"New Window" does not work in 0.3.2

### ISSUE THREAD

**Issue by deeplow** [freedomofpress/dangerzone#204]
When one opens a new window from the tray menu, on the `0.3.2 release` we get the following error:

```python
Traceback (most recent call last):
  File "/home/user/dangerzone/dangerzone/gui/__init__.py", line 91, in select_document
    and windows[list(windows.keys())[0]].common.input_filename == None
  File "/home/user/dangerzone/dangerzone/common.py", line 23, in input_filename
    raise RuntimeError("Input filename has not been set yet.")
RuntimeError: Input filename has not been set yet.
````

**Comment by deeplow** [comment]
Even though this is a regression from the previous release, from my testing on `0.3.1` (previous release) an additional bug related to this had gone unnoticed. I have reported it [now](https://github.com/freedomofpress/dangerzone/issues/205).

So, in short, even though this is a regression in terms of UX (window buttons don't work), it is not a regression compared to the previous release in terms of functionality.

**Comment by deeplow** [comment]
Oddly this doesn't seem to affect MacOS

**Comment by eloquence** [comment]
The "New Window" systray feature no longer exists in the development version and has been replaced with multi-document support, closing.
