### ISSUE TITLE
Re-evaluate container dependencies to mitigate potential CVEs

### ISSUE THREAD

**Issue by deeplow** [freedomofpress/dangerzone#232]
We can improve the security on the same level as #222 by reducing the software we ship in the container and replace vulerability-prone software.

This includes a re-evaluation of the software in [`container/dangerzone.py`](https://github.com/freedomofpress/dangerzone/blob/v0.3.2/container/dangerzone.py) and [`container/Dockerfile`](https://github.com/freedomofpress/dangerzone/blob/v0.3.2/container/Dockerfile).

Notable examples are:
  - removing `sudo` dependency
  - GraphicsMagick - used in the first (more exposed container) as well as in the second one. The Qubes
  - Libreoffice - perhaps shipping a headless / more stripped down version
  - supply chain security: making sure we only download packages from verified sources (in particular [PDFtk](https://github.com/freedomofpress/dangerzone/blob/v0.3.2/container/Dockerfile#L81))

**Comment by apyrgio** [comment]
I'd add removing `sudo` in the above list. Other than that, I fully agree.

**Comment by deeplow** [comment]
### Removing `openjdk-8` dependecy

`default-jre` and java dependencies dependencies had been added initially [because of libreoffice-java-common](https://github.com/firstlookmedia/dangerzone-converter/commit/9ecdb9e9952dc52b2ad973694aaeef4ba9e8f8ea), which is no longer present.

Then, when the image [was changed from ubuntu to alpine](https://github.com/firstlookmedia/dangerzone-converter/commit/650ae6eee13da6dc3b8d2f1ac8a70c9c52ab7e20), default-jre was replaced with openjdk-8.

If java is still a dependency for libreoffice, then it should be pulled automatically. There should be no need to state it explicitly. And tests pass.
