### ISSUE TITLE
Feature Request: Convert HWP files (Hancom Office)

### ISSUE THREAD

**Issue by CR0CKER** [freedomofpress/dangerzone#243]
It would be hugely helpful if Dangezone was capable of converting HWP files produced by Hancom Office, a terrible office suite that's extremely widely used in South Korea and frequently used for targeted malware attacks against journalists, researchers, defectors, and politicians in South Korea.

**Comment by apyrgio** [comment]
Thanks a lot for bringing this to our attention. It definitely looks like something Dangerzone should support.

Looking into HWP, I see that there are several open source projects that are trying to convert HWP files to ODT:

* https://github.com/mete0r/pyhwp
* https://github.com/k2webtech/hwp2odt

Have you tried any of them, or know if something else is more reliable? If we can rely on such a tool, we can use it as a pre-conversion step for HWP files, to grab an ODT document, and then let Dangerzone continue the conversion process as usual.

**Comment by CR0CKER** [comment]
Thanks for flagging these -- I'll have a look. So far I've only tried the HWP import in LibreOffice but compatibility was very poor, mostly because the HWP format apparently changed significantly in recent years and Hancom -- surprise -- has no interest in properly documenting the format.

**Comment by apyrgio** [comment]
Duly noted. Most probably this won't be part of the upcoming 0.4.0 release, but it would be nice providing support for 0.5.0 onwards. I'll keep this issue open to track this request.

One more thing I'd like to ask is what else would help Dangerzone users in South Korea? Are translations, alternative installation sources or stuff like that important to users in South Korea? Are other things more important?

**Comment by CR0CKER** [comment]
While not important to me, a Korean interface would certainly be useful. I'll follow up with further suggestions once I have more experience using this.

**Comment by CR0CKER** [comment]
Unfortunately I have not been able to test Dangerzone because converting a PDF fails with the following error message: 
<img width="593" alt="Screenshot 2022-11-17 at 2 51 42 PM" src="https://user-images.githubusercontent.com/6056387/202367267-ade25765-4741-492b-a16e-f13417eb969a.png">

Any idea what may cause this? Docker installed fine.

**Comment by apyrgio** [comment]
Interesting. It seems that the Docker daemon runs (else Dangerzone would have complained at startup), but the Dangerzone container does not start.

Can you please open a terminal, run the following commands, and provide the output here?

```
sudo docker info
sudo docker run hello-world
```

**Comment by CR0CKER** [comment]
Here's what I got:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.9.1)
  compose: Docker Compose (Docker Inc., v2.12.1)
  dev: Docker Dev Environments (Docker Inc., v0.0.3)
  extension: Manages Docker extensions (Docker Inc., v0.2.13)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.21.0)
```

```
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
2db29710123e: Pull complete 
Digest: sha256:faa03e786c97f07ef34423fccceeec2398ec8a5759259f94d99078f264e9d7af
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

```

**Comment by apyrgio** [comment]
I see, thanks for the command outputs. It seems that you can run containers, so we've covered that.

Next thing I'd like to ask is if this happens with other file names. For instance, I see that this filename has spaces in it. I recall we've fixed some space issues in the upcoming 0.4.0 release. Could you create a copy of this document with no spaces and test again?

**Comment by deeplow** [comment]
I have moved the conversation on the "invalid JSON" bug to [this new issue ](https://github.com/freedomofpress/dangerzone/issues/253) to keep the discussion organized. (how I miss discourse's "split thread" feature to preserve the original authors instead of quoting...)

**Comment by apyrgio** [comment]
Good call. I didn't know GitHub had this option for comments. Let's keep this issue for the HWP support then.

**Comment by OctopusET** [comment]
Here's open source version of LibreOffice HWP to ODT convertor. It also supports HWPX format.
https://github.com/ebandal/H2Orestart

**Comment by OctopusET** [comment]
@apyrgio Hello, I'm trying to add this plugin to dangerzone, but it's java based plugin so it need a JRE. Do you think is it possible to include JRE on the dangerzone?
