### ISSUE TITLE
Feature Request: Flatpak Version

### ISSUE THREAD

**Issue by zookeeper76** [freedomofpress/dangerzone#245]
I know this was brought up a few years ago but what is the status of having Dangerzone ported to Flatpak? 

Thank you for this great piece of software that helps protect many from powerful adversaries!

**Comment by apyrgio** [comment]
Let's bring the original issue into context btw: https://github.com/freedomofpress/dangerzone/issues/45
 
For the time being, this is not actively worked on. For the upcoming 0.4.0 release, we wanted to prioritize parallel document conversion, some defense in depth issues, and doing a full release under the Freedom of the Press Foundation umbrella. We have to see if this will fit in the 0.5.0 release, but this will depend on several factors (what benefits the users most, project sustainability, etc.). I can say though that now that we use Podman, we're closer to supporting it.

I propose we close this issue for now, in favor of the original Flatpak issue. If you have any other comments, feel free to echo them in that issue.
