### ISSUE TITLE
Use `ruff` for linting, code formatting and module sorting

### ISSUE THREAD

**Issue by apyrgio** [freedomofpress/dangerzone#254]
The codebase has several unused imports, that a linter could warn against. Find a linter for this job and use it as part of our `make lint` action.

**Comment by apyrgio** [comment]
Our `make lint` command currently employs three linters, none of which has an option to warn on unused imports:

1. For Black, see https://github.com/psf/black/issues/86.
2. For isort, see https://github.com/PyCQA/isort/issues/1105
3. For mypy, see https://github.com/python/mypy/issues/865

The rationale is that the are other tools for this job, such as `pylint`, `flake8`, and `autoflake`.

**Comment by legoktm** [comment]
flake8 is typically used for this purpose, I would recommend it in general as a pretty fast general purpose linter.

**Comment by deeplow** [comment]
I have done this [in the past](https://github.com/freedomofpress/dangerzone/pull/170#issuecomment-1219357080) in Dangerzone. But I don't recall what I used.

**Comment by almet** [comment]
Generally speaking, ruff seems the goto project for linting and formatting these days, and it's providing hints for this: https://docs.astral.sh/ruff/rules/unused-import/.

**Comment by jkarasti** [comment]
I'd like to work on this. I've been planning on opening a PR for a while now actually, but I've mostly focused on wrangling the Dangerzone Windows installer and WiX Toolset. But maybe as a fun weekend project...

**Comment by almet** [comment]
> I'd like to work on this. I've been planning on opening a PR for a while now actually, but I've mostly focused on wrangling the Dangerzone Windows installer and WiX Toolset. But maybe as a fun weekend project...

Great, don't hesitate to do it and let us know, it'll be a welcome addition 👍

**Comment by jkarasti** [comment]
> > I'd like to work on this. I've been planning on opening a PR for a while now actually, but I've mostly focused on wrangling the Dangerzone Windows installer and WiX Toolset. But maybe as a fun weekend project...
> 
> Great, don't hesitate to do it and let us know, it'll be a welcome addition 👍

Finally got around to opening the PR see #1019
