### ISSUE TITLE
Fix failing CI tests

### ISSUE THREAD

**Issue by apyrgio** [freedomofpress/dangerzone#292]
Our CI tests have recently started to fail on their own, due to upstream changes. See an example CI run [here](https://app.circleci.com/pipelines/github/freedomofpress/dangerzone/745/workflows/ebd8bfd3-5226-478c-afe5-c4ddb26cbbf5).

We see 3 tests that are failing:

1. `run-lint`: The `poetry install` command fails with exit code `1`, and no log message.
2. `build-debian-bookworm`: The "Install dependencies (deb)" task fails with `Unable to locate package python-all`.
3. `convert-test-docs`: The "Install poetry dependencies" step fails with:

     ```
     ERROR: launchpadlib 1.10.13 requires testresources, which is not installed.
     ERROR: importlib-resources 5.10.1 has requirement zipp>=3.1.0; python_version < "3.10", but you'll have zipp 1.0.0 which is incompatible.
     ```

**Comment by apyrgio** [comment]
# Fixing `build-debian-bookworm`

If we remove the `python-all` package from the list of the packages we install, then the package builds successfully in that platform. However, it fails to build on Ubuntu Focal with:

```
Writing dangerzone-0.4.0/setup.cfg
creating dist
Creating tar archive
removing 'dangerzone-0.4.0' (and everything under it)
dpkg-query: no packages found matching python-all
ERROR running: /usr/bin/dpkg-query --show --showformat=${Version} python-all
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    setuptools.setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/stdeb/command/bdist_deb.py", line 22, in run
    self.run_command('sdist_dsc')
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/stdeb/command/sdist_dsc.py", line 135, in run
    build_dsc(debinfo,
  File "/usr/lib/python3/dist-packages/stdeb/util.py", line 1369, in build_dsc
    python_defaults_version_str = get_version_str('python-all')
  File "/usr/lib/python3/dist-packages/stdeb/util.py", line 268, in get_version_str
    stdout = get_cmd_stdout(args)
  File "/usr/lib/python3/dist-packages/stdeb/util.py", line 243, in get_cmd_stdout
    raise RuntimeError('returncode %d', returncode)
RuntimeError: ('returncode %d', 1)
Traceback (most recent call last):
  File "./install/linux/build-deb.py", line 43, in <module>
    main()
  File "./install/linux/build-deb.py", line 34, in main
    run(["python3", "setup.py", "--command-packages=stdeb.command", "bdist_deb"])
  File "./install/linux/build-deb.py", line 20, in run
    subprocess.run(cmd, cwd=root, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python3', 'setup.py', '--command-packages=stdeb.command', 'bdist_deb']' returned non-zero exit status 1.

Exited with code exit status 1
```

**Comment by apyrgio** [comment]
# Fixing `run-lint`

I tried to reproduce the error locally, in a `debian:bullseye` container. Unfortunately, I didn't manage to, since the `poetry install` command always ran to completion. I tested if the issue manifests when the standard streams are not TTYs, and the command still succeeded.

Possible causes for this issue may be:
1. Changes to the CircleCI runners
2. Changes to the Poetry package on PyPI

In both cases, we would need to continue the debugging in a CircleCI runner. There is a way to avoid all this hassle though, and even improve this step:

1. Change the base image for this step from `debian:bullseye` to `debian:bookworm`.
2. Install `python3-poetry` from the official repos, instead of downloading it from PyPI. This has the benefit of using more stable versions of Poetry than the latest ones in PyPI.
     * By default, installing `python3-poetry` brings lots of packages with it, some of them GUI related. We can skip those with `--no-install-recommends`.
3. Because Debian Bookworm provides `python-poetry==1.2.2`, we can use the `--only dev` flag, and install only the dev dependencies.

With this change, `run-lint` passes, and we reduce the running time of the test from 1m19s to 59s.

**Comment by apyrgio** [comment]
# Fixing `convert-test-docs`

Turns out that this step does not fail with this error:

```
ERROR: launchpadlib 1.10.13 requires testresources, which is not installed.
ERROR: importlib-resources 5.10.1 has requirement zipp>=3.1.0; python_version < "3.10", but you'll have zipp 1.0.0 which is incompatible.
```

Instead, it fails for the same reason that `run-lint` fails, i.e., due to a Poetry 1.3 bug: https://github.com/python-poetry/poetry/issues/7184. A simple workaround for now is to pin Poetry to 1.2.2, and then remove the pin once it's fixed upstream, as it affects only installations from PyPI.

Note that we also tested replacing machine runner `ubuntu-2004` with `ubuntu-2204`, and install Poetry from the official repos. Turns out that they provide only Poetry 1.1, but we need Poetry 1.2, which supports the [group syntax.](https://python-poetry.org/docs/master/managing-dependencies/#dependency-groups)

**Comment by deeplow** [comment]
#### Fixing `debian-bookworm`
> With the above changes, we greatly simplify the build dependencies, and shave off roughly half a minute from each build step.

Thanks for the careful analysis. I am inclined to agree with this assessment. Minimizing the dependencies will also decrease the chance of dependency issues in the future.


#### Fixing `run-lint`

> In both cases, we would need to continue the debugging in a CircleCI runner. There is a way to avoid all this hassle though, and even improve this step:

Great! Since this is only linting, it shouldn't matter that much which version we're running.
