### ISSUE TITLE
Update project maintainers

### ISSUE THREAD

**Issue by apyrgio** [freedomofpress/dangerzone#343]
Freedom of the Press Foundation adopted Dangerzone from Micah Lee (and First Look Media) on mid-2022 ([source](https://freedom.press/news/welcome-to-the-dangerzone/)). As a result, the https://dangerzone.rocks domain got transferred to FPF (https://github.com/freedomofpress/dangerzone.rocks) and some disclaimers were added in documents that the public would read.

Code-wise though, there are still some things left for a full transition to FPF. I'll try to summarize those below, and offer my suggestions. Please correct me if I get something wrong:

### Authors/Maintainers

The author for the Python package (and consequently the rest of the system packages) is:

https://github.com/freedomofpress/dangerzone/blob/9b3d98b20b4ae25cf011fde70b5f60d4c926240a/pyproject.toml#L5

I propose changing this to `["Freedom of the Press Foundation <info@freedom.press>", "Micah Lee <micah.lee@theintercept.com>"]`, since you can refer in this field to the original authors ([source](https://peps.python.org/pep-0621/#authors-maintainers)).

In places where there is only one field for authors/maintainers, e.g.:

https://github.com/freedomofpress/dangerzone/blob/9b3d98b20b4ae25cf011fde70b5f60d4c926240a/setup.py#L22-L23

I propose changing it to:

```
author="Freedom of the Press Foundation",
author_email="info@freedom.press",
```

### Copyright

Currently, the copyright in our license is:

https://github.com/freedomofpress/dangerzone/blob/9b3d98b20b4ae25cf011fde70b5f60d4c926240a/LICENSE#L1-L3

I propose changing this to:

```
MIT License

Copyright (c) 2022-2023 Freedom of the Press Foundation
Copyright (c) 2020-2021 First Look Media
```

### References

1. In our README we offer this URL for more info on Dangerzone: https://tech.firstlook.media/dangerzone-working-with-suspicious-documents-without-getting-hacked. I propose replacing it with https://dangerzone.rocks/about.html, which is more up to date.
2. The publisher homepage is currently https://tech.firstlook.media. I believe the equivalent is https://freedom.press.

### Application URIs

Desktop application typically register themselves under a URI (see [Reverse domain name notation](https://en.wikipedia.org/wiki/Reverse_domain_name_notation)). The URI that Dangerzone uses is currently `media.firstlook.dangerzone`. I propose replacing it with `press.freedom.dangerzone`.

### MacOS Developer ID

The developer ID for MacOS is currently `FIRST LOOK PRODUCTIONS, INC. (P24U45L8P5)`. We should change this to the appropriate one for FPF, most likely `FREEDOM OF THE PRESS FOUNDATION, 501(c)(3)`.

### Windows Developer ID

The project currently refers to a signing certificate that is in possession of First Look Media:

https://github.com/freedomofpress/dangerzone/blob/9b3d98b20b4ae25cf011fde70b5f60d4c926240a/install/windows/build-app.bat#L8-L10

We need to change this to FPF's certificate.

### Windows Registry Keys

The Windows Registry key for Dangerzone is:

https://github.com/freedomofpress/dangerzone/blob/9b3d98b20b4ae25cf011fde70b5f60d4c926240a/install/windows/build-wxs.py#L74-L76

I propose renaming it to `Software\Freedom of the Press Foundation\Dangerzone`. Conversely, we can change the manufacturer from `First Look Media` to `Freedom of the Press Foundation`.

**Comment by eloquence** [comment]
I would be in favor of creating a dangerzone@freedom.press alias and just using "Dangerzone Team <dangerzone@freedom.press>" wherever we specify a maintainer. Would that work for you @micahflee @apyrgio @deeplow ?

The copyright statement works for me (I personally tend to default to a format like "2022-", but lawyerfolk tend to prefer the explicit end year -- either is fine with me, but if we specify an end year, we'll have to keep updating it).
