### ISSUE TITLE
Requires Docker Desktop (mac os 13.2.1 on m2)

### ISSUE THREAD

**Issue by Scr1p-tak** [freedomofpress/dangerzone#374]
Dangerzone 0.4.0
Docker Desktop 4.17.0
Mac OS 13.2.1

After instlling Dangerzone it ask for Docker Desktop.
I installed Docker Desktop with the given link in dangerzone.
After the install , the message was still there, app not usable.
Restarted the system. problem still there.
reinstalled dangerzone and docker-desktop (with homebrew and with .dmg , in all 4 conbinations)
Problem still there. Is this like a permission problem from dangerzone or PATH problem with Docker?

**Comment by deeplow** [comment]
Thanks for reporting the issue. After installing Docker Desktop the message changes to request you to start docker desktop. Do you remember starting it?

If not, please try the following:
  - start Docker Desktop
  - waiting a minute or to for the status indicator (bottom-left corner of Docker) to turn green
  - then opening Dangerzone
?

**Comment by Scr1p-tak** [comment]
> Thanks for reporting the issue. After installing Docker Desktop the message changes to request you to start docker desktop. Do you remember starting it?
> 
> If not, please try the following:
> 
> * start Docker Desktop
> * waiting a minute or to for the status indicator (bottom-left corner of Docker) to turn green
> * then opening Dangerzone
<img width="917" alt="screen" src="https://user-images.githubusercontent.com/93429315/227937292-8bd40c08-dc81-4da7-92b0-af5c949e20fc.png">

Did that, also restarted Docker-Desktop and Dangerzone.

**Comment by Scr1p-tak** [comment]
How does dangerzone check if docker desktop is installed?

**Comment by deeplow** [comment]
Thanks for the quick response. Then it seems like a problem where Dangerzone is not detecting properly docker.

> How does dangerzone check if docker desktop is installed?

It does[ `shutil.which('docker')`](https://github.com/freedomofpress/dangerzone/blob/main/dangerzone/isolation_provider/container.py#L54), which should be the equivalent of running in the terminal `which docker`.

Can you try installing the dmg and running via the terminal? You can do this by running:
`/Applications/Dangerzone.app/Contennts/MacOS/dangerzone-cli` with a document as the first argument.

It could be that the GUI version doesn't detect docker but the CLI detects it. We've had this issue in the past.

**Comment by deeplow** [comment]
Thanks for the quick response. Then it seems like a problem where Dangerzone is not detecting properly docker.

> How does dangerzone check if docker desktop is installed?

It does[ `shutil.which('docker')`](https://github.com/freedomofpress/dangerzone/blob/main/dangerzone/isolation_provider/container.py#L54), which should be the equivalent of running in the terminal `which docker`.

Can you try installing the dmg and running via the terminal? You can do this by running:
`/Applications/Dangerzone.app/Contennts/MacOS/dangerzone-cli` with a document as the first argument.

It could be that the GUI version doesn't detect docker but the CLI detects it. We've had this issue in the past.

**Comment by deeplow** [comment]
Thanks for the quick response. Then it seems like a problem where Dangerzone is not detecting properly docker.

> How does dangerzone check if docker desktop is installed?

It does[ `shutil.which('docker')`](https://github.com/freedomofpress/dangerzone/blob/main/dangerzone/isolation_provider/container.py#L54), which should be the equivalent of running in the terminal `which docker`.

Can you try installing the dmg and running via the terminal? You can do this by running:
`/Applications/Dangerzone.app/Contennts/MacOS/dangerzone-cli` with a document as the first argument.

It could be that the GUI version doesn't detect docker but the CLI detects it. We've had this issue in the past.

**Comment by deeplow** [comment]
(github outage messed up the "comment" button)

**Comment by Scr1p-tak** [comment]
when I run 'which docker' in the terminal it returns 'docker not found' .
But in the activity monitor , there is a docker process running in '/Applications/Docker.app/Contents/MacOS/Docker'.

When I run dangerzone-cli , it is almost the same.
Assigning ID 'JxPNOi' to doc '/Users/anastasioskougioumtzidis/test.pdf'
Traceback (most recent call last):
  File "dangerzone", line 13, in <module>
  File "click/core.py", line 1130, in __call__
  File "click/core.py", line 1055, in main
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "dangerzone/errors.py", line 103, in wrapper
  File "dangerzone/cli.py", line 75, in cli_main
  File "dangerzone/container.py", line 59, in install
  File "dangerzone/container.py", line 103, in is_container_installed
  File "dangerzone/container.py", line 51, in get_runtime
dangerzone.container.NoContainerTechException: docker is not installed
[77192] Failed to execute script 'dangerzone' due to unhandled exception: docker is not installed
[77192] Traceback:
Traceback (most recent call last):
  File "dangerzone", line 13, in <module>
  File "click/core.py", line 1130, in __call__
  File "click/core.py", line 1055, in main
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "dangerzone/errors.py", line 103, in wrapper
  File "dangerzone/cli.py", line 75, in cli_main
  File "dangerzone/container.py", line 59, in install
  File "dangerzone/container.py", line 103, in is_container_installed
  File "dangerzone/container.py", line 51, in get_runtime
dangerzone.container.NoContainerTechException: docker is not installed

Could this be because I installed docker-desktop with brew?

**Comment by deeplow** [comment]
> Could this be because I installed docker-desktop with brew?

Good hypothesis. Let me check that on my system.

**Comment by apyrgio** [comment]
> Could this be because I installed docker-desktop with brew?

Actually, this issue may be specific to your MacOS model and Homebrew installation. We see [here](https://earthly.dev/blog/homebrew-on-m1/) that on Mac M1 laptops, you need to do a further step to add the binaries installed by Homebrew to the path. If you have a Mac M1 indeed, can you verify that `/opt/homebrew` is in your `$PATH`? Running `brew doctor` could be an option as well.

**Comment by Scr1p-tak** [comment]
the bin for docker is in /opt/homebrew/Caskroom/docker/4.17.0,99724/Docker.app/Contents/Resources/bin/docker , and I have
' /opt/homebrew$'
'/opt/homebrew/opt/swift/bin$'
'/opt/homebrew/bin$'
'/opt/homebrew/sbin$'
'/usr/local/bin$'
in my PATH. 
But the direct docker path has a version number. so it would change the path with every update.
And docker is not in the above listed directories.

**Comment by Scr1p-tak** [comment]
> > Could this be because I installed docker-desktop with brew?
> 
> Actually, this issue may be specific to your MacOS model and Homebrew installation. We see [here](https://earthly.dev/blog/homebrew-on-m1/) that on Mac M1 laptops, you need to do a further step to add the binaries installed by Homebrew to the path. If you have a Mac M1 indeed, can you verify that `/opt/homebrew` is in your `$PATH`? Running `brew doctor` could be an option as well.

Ok I ran brew doctor (thought it was a typo/autocompletion 'docker / doctor' and  linked the keg.
Now the which docker command returns '/opt/homebrew/bin/docker'

We have progress. Running the dangerzone-cli now works. I can see in docker-desktop how it creates the containers and also deletes them after it finishes. 

But dangerzone gui still does not work.

**Comment by deeplow** [comment]
>  Now the which docker command returns '/opt/homebrew/bin/docker'

I was able to get this result by running `brew install docker. In this situation Dangerzone failed to detect it. I think this is because when Dangerzone is running it has the default path and the homebrew PATH mods don't get sourced.

After removing that docker and installing with `brew install --cask docker`. Then Dangerzone did work.

**Comment by deeplow** [comment]
When installing the Cask I think it's the same as downloading docker desktop from the official website via the .dmg

**Comment by apyrgio** [comment]
Dummy question, but could it be that your current user session does not have the proper `$PATH` when you spawn Dangerzone from GUI? That is, could you log out  and log back in?

**Comment by Scr1p-tak** [comment]
> Dummy question, but could it be that your current user session does not have the proper `$PATH` when you spawn Dangerzone from GUI? That is, could you log out and log back in?

Did not work. I restarted the Mac completely .

**Comment by Scr1p-tak** [comment]
> > I am using brew install --cask docker.
> > What did you do different ? Because I don't have docker in /usr/local/bin/
> 
> No idea.
> 
> > Funny is that if I uninstall docker with brew uninstall --cask docker , it ask for permission to delete docker from /usr/local/bin
> 
> Indeed. According the the source of the cask it does in fact expect to [delete it from there](https://github.com/nandahkrishna/homebrew-cask/blob/13370c6bea164cb045f92813c7867135a9109c65/Casks/docker.rb#L62).

Also , it does not ask for permissions when installing. So it does not even try to write the file to `/usr/local/bin`

**Comment by Scr1p-tak** [comment]
This is not the best solution 
`sudo ln -s /opt/homebrew/bin/docker /usr/local/bin/docker`
but it works. 

Thank you

**Comment by deeplow** [comment]
Glad it's been resolved. Since this is not a supported configuration I don't think we'll have to fix this in code. Only a very small subset of users will find this. But it's good for us to be aware.

Thanks again, @Scr1p-tak

**Comment by dltj** [comment]
Oddly, the [latest docker.rb Cask definition](https://github.com/Homebrew/homebrew-cask/blob/b32c6340c02ca558bd37e78c37f640bd73f1482f/Casks/docker.rb) doesn't seem to symlink the docker executable onto the path (although it will happily delete such a symlink if it is there). I found I had to do this on my Intel Mac:

```bash
ln -s  /Applications/Docker.app/Contents/Resources/bin/docker /usr/local/bin/docker
```

**Comment by kgadek** [comment]
I have the same problem. macOS 13, M1, `docker` installed via brew. Interestingly, my `docker` binary is in `~/.docker/bin`. `dangerzone-cli` works for me, as I have properly configured PATHs.

Would it be possible to add configuration for appending (or prepending or overriding) PATHs for dangerzone?

**Comment by apyrgio** [comment]
Hey @kgadek, sorry for jumping in late here.

In my experience, it's not typical for a program to have a setting about the path where it will look for executables. Especially Dangezone, which does not rely on many external programs.

In my opinion, configuration issues like that should be resolved at the system level, so that CLI applications and GUIs can benefit alike. MacOS is not my daily driver, but I see that others have found a [solution to this](https://stackoverflow.com/a/26586170). Hopefully it helps.

Alternatively, other solutions like symlinking can also help, and they apply to the whole system as well.
