### ISSUE TITLE
Image Building: deal with "podman save" failures (fail early)

### ISSUE THREAD

**Issue by deeplow** [freedomofpress/dangerzone#380]
When building the image, for some reason on my system, the podman failed on the `podman save` command but exited with 0 because gzip succeeded:

```
podman save $TAG | gzip > share/container.tar.gz
```

Here's the output:

```
Successfully tagged dangerzone.rocks/dangerzone:latest
b255ed5e7e290a7e826e853839192b4deb798410f977449f4a46e1a28e786c76
Saving and compressing container image
Error: reading blob sha256:0a1c2eca4ebe0f648267083c3740ff6af91e6386b68d35f2d7bf0c40b141dac3: error locating image with ID "b255ed5e7e290a7e826e853839192b4deb798410f977449f4a46e1a28e786c76": image not known
Looking up the image id
```

## Solution

[`set -o pipefail`](https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html)

**Comment by apyrgio** [comment]
Closing this issue, as this has been fixed by https://github.com/freedomofpress/dangerzone/pull/721.
