### ISSUE TITLE
The opened application should be recognised as a dangerzone by Fedora 38 with GNOME Desktop

### ISSUE THREAD

**Issue by sudwhiwdh** [freedomofpress/dangerzone#402]
![02](https://user-images.githubusercontent.com/58292468/235186603-132fdf5d-a4ee-4f85-8387-7db023fa8a64.png)
![07](https://user-images.githubusercontent.com/58292468/235186612-3e951184-464c-4a1e-8ea8-193192d3f1e4.png)
![01](https://user-images.githubusercontent.com/58292468/235186614-97fbe76f-5c15-42df-ad24-84c7e9e148a3.png)

Instead, python3 is displayed in various places (here Dock, Panel, Window Overview)

My wish would be that "dangerzone" is displayed together with the appropriate application icon.

**Comment by apyrgio** [comment]
Right, I can reproduce this locally, but I never managed to dig deeper. Our `.desktop` file uses the "dangerzone" name everywhere, so maybe we are missing a field that Gnome understands.

**Comment by sudwhiwdh** [comment]
@apyrgio Is still present in version 0.4.2.

**Comment by apyrgio** [comment]
Sigh, it most probably is, since we haven't found the time to work on it. It's one of these issues that are not bugs or new features, so they stay for a bit more in the back burner. I have tagged it as `good first issue` though, and I encourage newcomers that want to assist in Dangerzone's development to take a stab at it.

**Comment by deeplow** [comment]
This issue will probably be a bit about finding the proper directory to install the desktop icon.

Here's a section of [a related discussion](https://github.com/freedomofpress/dangerzone/pull/538#discussion_r1321683424):
> The location you're seeing is the one where we previously installed this icon. You're right for pointing this out, and I think this may affect https://github.com/freedomofpress/dangerzone/issues/402. Still, I'd suggest tackling it in a different PR, if you don't mind, since I bet we will go into a rabbit hole.

**Comment by apyrgio** [comment]
We are still bitten by this as @deeplow found out in our recent QA for 0.5.1 (https://github.com/freedomofpress/dangerzone/issues/634#issuecomment-1845715552). Apologies, and I hope we can have a fix out in time.

**Comment by apyrgio** [comment]
I think we have a fix here, which I've verified it works in Fedora 39 (see #774). If we set in our application:

```python
self.setDesktopFileName("press.freedom.dangerzone")
self.setApplicationName("dangerzone")
```

then the correct icon, application ID, and name, is reported as well. Depending on the OS, only the desktop file name may be needed, but we want to set both to leave no room for ambiguity.
