### ISSUE TITLE
Better output for docker pull

### ISSUE THREAD

**Issue by micahflee** [freedomofpress/dangerzone#41]
When pulling the container image, it displays stdout in the GUI. However, when you run `docker pull flmcode/dangerzone` the output is _way_ more informative, showing you the different chunks and progress bars for each one. I'd like to make the GUI show the same.

**Comment by micahflee** [comment]
I think this is going to be complicated. One option is to use the Docker API instead of calling out to `docker pull`: https://docker-py.readthedocs.io/en/stable/api.html

But because it's more work than I realized, I'm removing the 0.2 milestone.

**Comment by deeplow** [comment]
Now we're just shipping the container image. It could use a progress bar, but I don't think that's too critical. For that reason I'm closing this issue. Feel free to reopen it if you think otherwise.
