### ISSUE TITLE
Qubes: Beta integration

### ISSUE THREAD

**Issue by apyrgio** [freedomofpress/dangerzone#412]
For Qubes OS Beta integration, users should be able to enjoy most of the important features that Dangerzone provides in the other platforms:

- [x] https://github.com/freedomofpress/dangerzone/issues/429
- [x] https://github.com/freedomofpress/dangerzone/issues/430
- [x] https://github.com/freedomofpress/dangerzone/issues/431
- [x] #446
- [x] #438 
- [x] https://github.com/freedomofpress/dangerzone/issues/455

Optional:
- [ ]  https://github.com/freedomofpress/dangerzone/issues/443

**Comment by deeplow** [comment]
> * :heavy_check_mark: OCR

This will present some challenges since alpine likely ships a different set of tesseract-ocr languages than fedora (on which our Qubes implementation be probably be based).

**Comment by deeplow** [comment]
> > * heavy_check_mark OCR
> 
> This will present some challenges since alpine likely ships a different set of tesseract-ocr languages than fedora (on which our Qubes implementation be probably be based).

No longer an issue thanks to https://github.com/freedomofpress/dangerzone/pull/422

**Comment by apyrgio** [comment]
Now that streaming support for containers has been postponed for another release, and the rest of the tasks have completed, we can officially close this issue :tada:
