### ISSUE TITLE
Qubes: RPM Packaging

### ISSUE THREAD

**Issue by deeplow** [freedomofpress/dangerzone#431]
Package Dangerzone for Qubes OS in a way that satisfies the following requirements:

* :heavy_check_mark: Do not include the container image, as is the case for the rest of our packages.
* :heavy_check_mark: Use the Qubes OS isolation provider (#414).
* :heavy_check_mark: Contain the dependencies necessary to run both the client and the dispVM parts of the conversion.
* :heavy_check_mark: Target the default Qubes OS template (Fedora 38 as of writing this).
* :heavy_check_mark: Avoid installing dangerzone-signed code in dom0
* :warning: Install the necessary Tesseract OCR data (see https://github.com/freedomofpress/dangerzone/issues/438#issuecomment-1689664488)
* :hourglass_flowing_sand: : Include it in our [freedomofpress/yum-tools-prod](https://github.com/freedomofpress/yum-tools-prod) repo.

Related discussions:
  - [What’s the Future Of Multi-VM Applications? (Qubes Forum)](https://forum.qubes-os.org/t/whats-the-future-of-multi-vm-applications-securedrop-workstation-inspired/18649)

**Comment by apyrgio** [comment]
## Installation instructions

Since template VMs don't have network attached, it would have been tricky installing Dangerzone, since we need to download keys, configuration, and the actual packages.

Thankfully, our existing commands:

```
sudo dnf config-manager --add-repo=https://packages.freedom.press/yum-tools-prod/dangerzone/dangerzone.repo
sudo dnf install dangerzone
```

all pass through the [updates proxy](https://www.qubes-os.org/doc/how-to-install-software/#updates-proxy).

**Comment by eloquence** [comment]
>  Enumerate all the tesseract language packages (123 as of writing this) within the RPM spec file.

As discussed in team meeting, that would be my vote for now. We'll want to a more robust approach to languages across platforms, with a lean default configuration and optional downloading ideally triggered via the UI. But I'd prefer to avoid doing something bespoke just for Qubes right now, also in terms of "principle of least surprise".
