### ISSUE TITLE
Windows 10:Invalid JSON returned from container

### ISSUE THREAD

**Issue by 0nly3rrors** [freedomofpress/dangerzone#469]
I am trying to scan an document inside windows 10 but when i do this i get this error "Invalid JSON returned from container".

**Comment by deeplow** [comment]
Thanks for reporting the issue. Can you hover with your mouse over the error message like this?

![tooltip](https://github.com/freedomofpress/dangerzone/assets/47065258/423f191b-a12e-403d-8bd6-8e428fe9526b)

The message in the tooltip should give some extra information as to what could be causing this issue.

**Comment by deeplow** [comment]
Other questions:
  - does this show the error immediately or do you see a progress bar before. If you see the progress bar, can you tell us what percentage it goes up to before failing?
  - does with happen with the OCR option enabled or disabled?
  - does this happen with every file or just a specific one? If it happens with all or multiple, is there any publicly available file where this happens that you can share with us?

**Comment by 0nly3rrors** [comment]
I tried three pdfs randomly from some sites.
This error shows up immediately.
I got the same error with checked and unchecked ocr button.

**Comment by apyrgio** [comment]
This starts to sound like a Docker problem. If you are comfortable with using the Windows command prompt (you can find it in your applications), can you run the following command and give us the output?

```
docker run hello-world
```

**Comment by apyrgio** [comment]
Hi @0nly3rrors. Do you have any update on this issue? Also, does the latest Dangezone release (0.4.2) work for you?

**Comment by 0nly3rrors** [comment]
I gave up and used a VM with Ubuntu instead @apyrgio

**Comment by apyrgio** [comment]
I'm sorry to hear that :-/. Our tests on Windows so far have not replicated this issue. It could be something local to your environment, but we'd need more debugging to find that. I'll close this for now, but if any other affected Windows 10 user stumbles on this, please re-open it.
