### ISSUE TITLE
Enable "Discussions" tab for user assistance & questions

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/dangerzone#473]
I suggest we enable the "Discussions" feature on GitHub to support conversations with our users. This allows for a bit more informal engagement than GitHub issues, and also enables user-to-user support. More info: https://docs.github.com/en/discussions

**Comment by apyrgio** [comment]
We now have a [discussion page](https://github.com/freedomofpress/dangerzone/discussions) :tada:

**Comment by deeplow** [comment]
I've added a task to further mention the existence of this https://github.com/freedomofpress/dangerzone.rocks/issues/25
