### ISSUE TITLE
Improve organization of installation docs

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/dangerzone#475]
Currently we have:

- minimal instructions for Windows/Mac in the README.md
- detailed instructions for Linux package repository configuration in INSTALL.md

There are a few issues with this:
- README.md does not make it sufficiently clear that you need to install Docker for Desktop to use Dangerzone on Mac or Windows. The app itself will warn the user about this, but we should state the prerequisites more clearly upfront. (Docker is mentioned a couple of times in the README, but not in the section with the download/install info.)
- INSTALL.md only covers Linux, which means that users who land on that guide may assume that Dangerzone is a Linux-only app.
- INSTALL.md also does not make the prerequisites for Linux clear (i.e. it does not mention Docker or Podman).

I would suggest that we take the following approach:
- Treat README.md as a "quickstart guide" that summarizes the steps needed on every supported platform
- Treat INSTALL.md as detailed installation instructions on every supported platform (and that may include reference to secondary installation options, such as Homebrew, which we might omit from the README for reasons of brevity)

**Comment by deeplow** [comment]
How does https://github.com/freedomofpress/dangerzone/pull/509 look? I think followed your advice mostly. The only thing that I didn't do was moving the homebrew note to INSTALL.md because it felt a bit out of palce there (all the other instructions for mac remained on README).
