### ISSUE TITLE
Update check does not place "Check for updates" checkmark in UI

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/dangerzone#513]
# Steps to reproduce

1. On a Mac, install and run Dangerzone so you get the update check prompt.
2. Confirm that you want automatic update checks.
3. Click the menu button to reveal the current state of the "update check" settings.

# Expected behavior

Update check should have a checkmark next to it, since I've enabled update checks

# Actual behavior

Checkmark is not set until I restart Dangerzone

**Comment by deeplow** [comment]
Thanks for spotting this. I can confirm the bug. I have a working fix.
