### ISSUE TITLE
Gracefully handle pdftoppm not failing when /tmp fills up

### ISSUE THREAD

**Issue by deeplow** [freedomofpress/dangerzone#524]
I notice that when I run on my host `pdftoppm`  with `/tmp` filled up to 100% and `pdftoppm` fails silently with exit code `0`, even though the final files are 0 in size.

This is probably an upstream issue.

**Comment by deeplow** [comment]
I was trying to find some more python native way of using this, but I couldn't find it:
  - **qubes-trusted-pdf** does it the same way we did before (PDF -> PNG -> RGB), which if we think about it is not terrible because at least they don't need to keep the RGBs
  - **I found the [pdf2image](https://github.com/Belval/pdf2image/blob/master/pdf2image/pdf2image.py#L265)** module, but it just uses pdf2ppm behind the scenes

If `pdftoppm` becomes too difficult to tame we can always resort to using it with `-singlefile`, calling one `pdftoppm` process per page... and that way we can send the RGB image as soon as it's done, delete the file and move to the next page.

**Comment by apyrgio** [comment]
We no longer use `pdftoppm`, and we have fixed all of the related out of space issues (see https://github.com/freedomofpress/dangerzone/issues/518)
