### ISSUE TITLE
(client) Handle RGB pages not fitting in temporary directories

### ISSUE THREAD

**Issue by apyrgio** [freedomofpress/dangerzone#526]
_(this issue is a follow up of https://github.com/freedomofpress/dangerzone/issues/518, best done after #443)_

The size of a single [A4 page in pixels](https://www.a4-size.com/a4-size-in-pixels/) is:
  
* 1 A4 page at 72 DPI = 595 x 842 pixels
* 1 A4 page at 150 DPI = 1240 x 1754 pixels
  
We also need to account for 3 color channels too (RGB), meaning that the final size in bytes is:

* 1 A4 page at 72 DPI = 3 x 595 x 842 pixels = 1.43 MiB
* 1 A4 page at 150 DPI = 3 x 1240 x 1754 pixels = 6.22 MiB
  
If we have 1 GiB of RAM available, we need 716 pages (72 DPI) or 165 pages (150 DPI) to fill it up. It seems that `pdftoppm` does use 150 DPI by default for the conversion to PPM, meaning that users with limited RAM (e.g., 1 GiB) will not be able to convert PDFs with more than **165** pages. Note that this is the case because we store the RGB files in a temporary directory as a result of the conversion to pixels.

This is a limitation that does not affect all users or files, but we need to find a solution for it.

**Comment by apyrgio** [comment]
We also need to find out if this affects Windows / MacOS platforms, i.e., if `tmpfs` is used there.

**Comment by deeplow** [comment]
> From the above solutions, it seems that (2) is the one we should go with.

I agree with this. And we can use the [pillow](https://pillow.readthedocs.io/en/stable/releasenotes/3.4.0.html) python module to convert from rgb to png (or if needed even PDF).

**Comment by apyrgio** [comment]
As part of #625, we no longer store RGB files in temporary directories. The safe PDF is now created on the fly, and each page is compressed immediately, once it's received from the conversion sandbox. This means that there will be at most 1 **uncompressed** RGB page in-flight at all times. The rest of the pages will be **compressed**, which really improves the situation.
