### ISSUE TITLE
Switch back to alpine:latest

### ISSUE THREAD

**Issue by apyrgio** [freedomofpress/dangerzone#542]
Switch back to `alpine:latest` from `alpine:edge`, once the `7.5.5.2-r2` package of [LibreOffice](https://pkgs.alpinelinux.org/package/v3.18/community/aarch64/libreoffice) lands in the stable repo.

See also #540 and #498

**Comment by deeplow** [comment]
Not sure this will be doable by `0.5.0`. If we don't get this done, should we revert those PRs?

**Comment by apyrgio** [comment]
I propose we simply move this feature to the next milestone (e.g., 0.5.1). After all, we have tested `edge` pretty thoroughly by now, and we know that Alpine Linux will [release a new version](https://www.alpinelinux.org/releases/) somewhere in November.

**Comment by apyrgio** [comment]
Update: in the end, we ended up switching to `alpine:latest`, and reverted the merged PR. For more info, see: https://github.com/freedomofpress/dangerzone/issues/498#issuecomment-1739894100

This issue can now close.
