### ISSUE TITLE
`pdftoppm` creates empty files when it runs out of space

### ISSUE THREAD

**Issue by apyrgio** [freedomofpress/dangerzone#576]
We have seen that the `pdftoppm` tool can create empty files, if it cannot write in them due to lack of space (`ENOSPC`). Worse, it doesn't fail its execution, leading to a cryptic "Error converting PDF to Pixels (Invalid PPM header)" error, when our callback handler attempts to convert PPM files to RGB.

This is something we have seen as a side-effect of #574. This lack of reliability is worrisome, so it's probably best to see if we can use another tool.

**Comment by apyrgio** [comment]
Actually, this error is a duplicate of an error @deeplow had already reported: #524. Closing this error in favor of the older one.

**Comment by deeplow** [comment]
Looks like you forgot to close it
