### ISSUE TITLE
Add git clone to BUILD instructions

### ISSUE THREAD

**Issue by mc-gitdeb** [freedomofpress/dangerzone#584]
I have poetry installed and added to my PATH but I can't seem to find my dangerzone folder,

Do I need to download something else first?

**Comment by deeplow** [comment]
This sounds more like a development question rather than an issue with Dangerzone, so I'll reply on our github discussions forum instead and close this. Let's continue the conversation here https://github.com/freedomofpress/dangerzone/discussions/585

**Comment by deeplow** [comment]
I have now added "git clone" instructions to the build instructions. Hopefully that makes it clearer. Thanks for bringing up the issue @mc-gitdeb.

Closed by https://github.com/freedomofpress/dangerzone/pull/594

**Comment by mc-gitdeb** [comment]
Thank you too,

Good job, very prompt 👍
________________________________
