### ISSUE TITLE
Flagged by Windows Defender SmartScreen

### ISSUE THREAD

**Issue by TheodoreChu** [freedomofpress/dangerzone#59]
After [downloading the .msi](https://github.com/firstlookmedia/dangerzone#getting-started) for Windows and run it, we get this:
![image](https://user-images.githubusercontent.com/22967798/76720781-fff00a80-66fa-11ea-810b-7a1e8ae9b8bc.png)

It seems to install fine when we click "Run Anyway," but I thought I should let you know

**Comment by deeplow** [comment]
I don't know how it was at the time, but now the app is signed with a valid windows certificate so this shouldn't happen anymore. Feel free to open it again if it does happen.
