### ISSUE TITLE
PySide DeprecationWarning: `exec_`->`exec`

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/dangerzone#595]
Seen in QA with Ubuntu 22.04 target during tests:

```
/home/user/dangerzone/dangerzone/gui/main_window.py:208: DeprecationWarning: 'exec_' will be removed in the future. Use 'exec' instead. update_widget.exec_()
```

Wasn't able to find any actual deprecation timeline, just complaints about lack of documentation for this deprecation :upside_down_face: https://bugreports.qt.io/browse/PYSIDE-1583

**Comment by deeplow** [comment]
I was already aware, but had not yet created an issue. Thanks for opening it.
