### ISSUE TITLE
[0.5.0/Ubuntu 22.04] "Check for updates" setting does not persist

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/dangerzone#596]
## Steps to reproduce

1. Create an Ubuntu 22.04 QA environment using `qa.py`
2. Run `dangerzone` inside the container
3. Toggle the "Check for updates" checkbox
4. Restart Dangerzone

## Expected behavior

Setting persists.

## Actual behavior

The checkbox is unchecked again on restart.

**Comment by deeplow** [comment]
What's interesting is that this appears to be working on my non-QA environment. I'll have to dig a bit deeper.

**Comment by deeplow** [comment]
I see that the settings file does change

```
9c9
<     "updater_check": false,
---
>     "updater_check": true,
```

The GUI however does not and I think I know why!

We were doing:

```python
bool(self.dangerzone.settings.get("updater_check"))
```
However, `bool("true")` is `True` just because a non-empty string is always True. Therefore, `bool("false")` is also True... :/

**Comment by deeplow** [comment]
Turns out that was **not** the real reason and the JSON is fine. I have a fix for it.
