### ISSUE TITLE
Original and Converted Document Dimentions Don't Match

### ISSUE THREAD

**Issue by deeplow** [freedomofpress/dangerzone#626]
Comment by @j75 from [another issue](https://github.com/freedomofpress/dangerzone/issues/620#issuecomment-1827401006):
> the original document (https://s1.q4cdn.com/806093406/files/doc_downloads/test.pdf) has Page size:   612 x 792 pts (letter) the test-safe.pdf document has Page size:  1275 x 1650 pts

I had just come across this as well: 

| | original size | converted size | 
|--|--|--|
|width (inches) | 8.27 | 17.73 
|height (inches) | 11.7 | 25.06
|width (points) | 595.28 | 1276.46
|height (points) | 841.89 | 1804.11

**Comment by j75** [comment]
`uses tesseract under the hood` - well, in this case there might be another issue (at least on Ubuntu) - the package **does not** depends on tesseract!
```
Depends: python3:any (>= 3.6~), podman, python3, python3-pyside2.qtcore, python3-pyside2.qtgui,
         python3-pyside2.qtwidgets, python3-pyside2.qtsvg, python3-appdirs, python3-click,
         python3-xdg, python3-colorama, python3-requests, python3-markdown, python3-packaging
```
In my case fortunately I already have this package installed, however in the general case I think it should be part of deb's dependencies.
