### ISSUE TITLE
 QA and Release 0.5.1

### ISSUE THREAD

**Issue by deeplow** [freedomofpress/dangerzone#634]
To ensure that new releases do not introduce regressions, and support existing and newer platforms, we have to do the following:

- [x] In `.circleci/config.yml`, add new platforms and remove obsolete platforms
- [x] Bump the Python dependencies using `poetry lock`
- [x] Make sure that the tip of the `main` branch passes the CI tests.
- [x] Make sure that the Apple account has a valid application password and has agreed to the latest Apple terms (see [macOS release](#macos-release) section).
- [x] Create a test build in Windows and make sure it works:
  - [x] Check if the suggested Python version is still supported.
  - [x] Create a new development environment with Poetry.
  - [x] Build the container image and ensure the development environment uses the new image.
  - [x] Run the Dangerzone tests.
  - [x] Build and run the Dangerzone .exe
  - [x] Test some QA scenarios (see [Scenarios](#Scenarios) below).
- [x] Create a test build in macOS (Intel CPU) and make sure it works:
  - [x] Check if the suggested Python version is still supported.
  - [x] Create a new development environment with Poetry.
  - [x] Build the container image and ensure the development environment uses the new image.
  - [x] Run the Dangerzone tests.
  - [x] Create and run an app bundle.
  - [x] Test some QA scenarios (see [Scenarios](#Scenarios) below).
- [x] Create a test build in macOS (M1/2 CPU) and make sure it works:
  - [x] Check if the suggested Python version is still supported.
  - [x] Create a new development environment with Poetry.
  - [x] Build the container image and ensure the development environment uses
    the new image.
  - [x] Run the Dangerzone tests.
  - [x] Create and run an app bundle.
  - [x] Test some QA scenarios (see [Scenarios](#Scenarios) below).
- [x] Create a test build in the most recent Ubuntu LTS platform (Ubuntu 22.04 as of writing this) and make sure it works:
  - [x] Create a new development environment with Poetry.
  - [x] Build the container image and ensure the development environment uses the new image.
  - [x] Run the Dangerzone tests.
  - [x] Create a .deb package and install it system-wide.
  - [x] Test some QA scenarios (see [Scenarios](#Scenarios) below).
- [x] Create a test build in the most recent Fedora platform (Fedora 38 as of writing this) and make sure it works:
  - [x] Create a new development environment with Poetry.
  - [x] Build the container image and ensure the development environment uses the new image.
  - [x] Run the Dangerzone tests.
  - [x] Create an .rpm package and install it system-wide.
  - [x] Test some QA scenarios (see [Scenarios](#Scenarios) below).
- [x] Create a test build in the most recent Qubes Fedora template (Fedora 38 as of writing this) and make sure it works:
  - [x] Create a new development environment with Poetry.
  - [x] Run the Dangerzone tests.
  - [x] Create a Qubes .rpm package and install it system-wide.
  - [x] Ensure that the Dangerzone application appears in the "Applications" tab.
  - [x] Test some QA scenarios (see [Scenarios](#Scenarios) below) and make sure they spawn disposable qubes.

_(see also the previous [QA for 0.5.0](https://github.com/freedomofpress/dangerzone/issues/534))_

**Comment by apyrgio** [comment]
Closing this issue, now that Dangerzone 0.5.1 has been released. QA-wise, we've opened this issue to track some improvements we can make in this section: https://github.com/freedomofpress/dangerzone/issues/641
