### ISSUE TITLE
`focal` no longer has a Release file

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/dangerzone#653]
It looks like something went wrong with the 0.5.1 Release file generation for `focal` and it went missing:
https://github.com/freedomofpress/apt-tools-prod/pull/10
https://packages.freedom.press/apt-tools-prod/dists/

**Comment by apyrgio** [comment]
Re-running the `./tools/publish` script completes successfully. Still, it doesn't create the Release files for focal.

**Comment by apyrgio** [comment]
This issue has been resolved by an update on apt-tools-prod.
