### ISSUE TITLE
Update CircleCI runners

### ISSUE THREAD

**Issue by apyrgio** [freedomofpress/dangerzone#681]
The Linux image we are using for the CircleCI runners has been deprecated (read the [official announcement](https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177)). Full deprecation will take place on September 30th, 2024, and intermittent outages (brownouts) are expected to start happening from February 26th.

By that date, we either need to bump the image of our runners (we have done so in the past without much trouble, or migrate to GitHub actions (#674).

**Comment by harrislapiroff** [comment]
Looks like there's another scheduled brownout on Aug 28 and then EOL on Sep 30. Let's prioritize this when @almet returns next week.

**Comment by apyrgio** [comment]
Just a quick update on this issue. We have partially updated our CircleCI machines for the various CI jobs we have (see #914). If we don't manage to make the CircleCI -> GitHub migration happen by Sep 30th, let's do it for the rest of the  CI jobs and close this issue.

Note that this is an artificial constraint that we put on ourselves, so that we feel the heat.

**Comment by apyrgio** [comment]
We have fully switched to GitHub actions, so we can close this issue.
