### ISSUE TITLE
Prevent FIXUP commits from being merged

### ISSUE THREAD

**Issue by deeplow** [freedomofpress/dangerzone#710]
Add a GitHub action that prevents merging if FIXUP is found the PR branch. This has happened twice recently and because our main is protected, this gets written to history.

**Comment by apyrgio** [comment]
@deeplow has added a CI check that fails if there's a commit with WIP/FIXUP in its title. It doesn't prevent pushes, but it's a good visual warning so that developers don't push to main, much as failing lints are.
