### ISSUE TITLE
Feature Request: .eml and .msg support

### ISSUE THREAD

**Issue by Owl-Tec** [freedomofpress/dangerzone#760]
Hi Everyone,

Any chance that Dangerzone will support .msg and .eml files in the future? 

The reason I ask is that I deal with a lot of phishing emails via the Microsoft 365 Security Admin Centre and to fully investigate if the emails (and their attachments) are safe or not I have to download them as .eml files, open the email, and then potentially investigate the attached files.

BTW - thanks for such a cool free app.

**Comment by supertr0n** [comment]
Just chiming in to say that is a nice idea that I could make use of too.  When dealing with .msg/.eml files, I would lose nothing by having them as PDFs instead - I don't actually need them in the original email format.  I would imagine this applies to a lot of people who routinely need to open such files.

So the ability to create a sanitised PDF directly from one of those file formats would be really useful.

I'm not in journalism but I would imagine this would be a valuable additional protection for those who are.

**Comment by apyrgio** [comment]
Yeap, this is a recurring question (see https://github.com/freedomofpress/dangerzone/issues/163). I definitely think it's valuable as well. Unfortunately, we have to tackle first some issues in our [0.7.0 milestone](https://github.com/freedomofpress/dangerzone/milestone/15) that have to do with the very core of Dangerzone. So, enhancements of this type will have to wait for a subsequent release.

Note that the latest release added `.epub` and `.svg` support, so we do take this kind of feedback seriously. In the meantime, I'll close this specific issue as duplicate. Feel free to resume the discussion in https://github.com/freedomofpress/dangerzone/issues/163.
