### ISSUE TITLE
Allow bulk conversion to safe PDFs

### ISSUE THREAD

**Issue by micahflee** [freedomofpress/dangerzone#77]
A few different people have requested this feature: the ability to convert documents to safe PDFs in bulk.

This shouldn't be too difficult to implement, but I think the biggest issue is how the user interface should work. One idea is to allow the user to browse for a folder, and then try to automatically convert all documents it can in that folder to save versions (appending `-safe.pdf` to the end). It probably makes sense to convert them one at a time, and also display a report of all unsupported files in the folder that couldn't get converted.

What happens if there's a file called `test.pdf` and another called `test-safe.pdf` in the same folder though? What would the safe version of `test.pdf` get named? It could maybe detect this edge case, and tell you that you must not have any files that end in `-safe.pdf` in the folder to convert.

**Comment by haplo** [comment]
> It probably makes sense to convert them one at a time, and also display a report of all unsupported files in the folder that couldn't get converted.

Running multiple conversions in parallel would improve running times and make use of multiple CPU cores. Just run a [process pool](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.pool.Pool) bound to the number of CPUs (ideally would be a configurable setting), queue all PDF to be converted (using [multiprocessing.Queue](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Queue) and have the worker processes pull from the queue and do the conversion. I can provide an implementation for this.

> What happens if there's a file called `test.pdf` and another called `test-safe.pdf` in the same folder though? What would the safe version of `test.pdf` get named? It could maybe detect this edge case, and tell you that you must not have any files that end in `-safe.pdf` in the folder to convert.

I think a good UX would be to identify all PDF files that already have a `-safe` version and skip them, telling the user that they seem to be already converted. User can then manually rename them if they want Dangerzone to work on them.

**Comment by pettitjr** [comment]
I would also like to see this feature!

**Comment by JesseKrembsNYT** [comment]
What James said..

**Comment by tzmnyt** [comment]
Bulk conversion of PDFs is very much needed.

**Comment by ritalawRL** [comment]
Bulk conversion is desperately needed here as well.

**Comment by DirtyNoob** [comment]
I agree to the consensus here, this is much needed!

**Comment by anarcat** [comment]
as part of #110, i implemented a webdav processor to do batch processing. the idea is that you dump your files in a webdav folder (e.g. on nextcloud), share that folder with the dangerzone bot, which pulls the files, processes them in docker, and pushes the sanitized files back.

see https://gitlab.torproject.org/tpo/tpa/dangerzone-webdav-processor/ for details.

**Comment by ninavizz** [comment]
Hey hey! I've got some hours to spare to get a nice UX together for this, and to potentially improve the single-file experience. Can do & share next week.

**Comment by deeplow** [comment]
An extra thing to consider is that a user may want to add extra files while some are already processing.

**Comment by eloquence** [comment]
Tentatively adding to 0.4.0 milestone; initially, this may only include backend changes to support bulk conversion + CLI support.
