### ISSUE TITLE
Unhandled exceptions occurring inside function passed to `executor.map` are swallowed

### ISSUE THREAD

**Issue by naglis** [freedomofpress/dangerzone#776]
Currently, if an unhandled exception occurs inside [`convert_doc`](https://github.com/freedomofpress/dangerzone/blob/7c4e62954f4ee71726de0a23655c8f791f05f290/dangerzone/logic.py#L75) when running `dangerzone-cli`, the exception is swallowed (traceback is not logged, the exit code is not changed).

This manifests in tests with dummy conversion - e.g. if [`shutil.copy`](https://github.com/freedomofpress/dangerzone/blob/7c4e62954f4ee71726de0a23655c8f791f05f290/dangerzone/isolation_provider/dummy.py#L65) raises an exception (e.g. `src` and `dst` being the same path), the `CLIResult` is still reported as a success due to the swallowed exception. [Here](https://github.com/naglis/dangerzone/commit/0d214c14d3c9045b9eeb7764fdedb55df4d9a5a3#diff-4e8715c7a425ee52e74b7df4d34efd32e8c92f3e60bd51bc2e1ad5943b82032eR222) is a demo test case.

IIUC during actual (not dummy) execution it would hide potential exceptions occurring [here](https://github.com/freedomofpress/dangerzone/blob/7c4e62954f4ee71726de0a23655c8f791f05f290/dangerzone/isolation_provider/base.py#L69-L70) or [here](https://github.com/freedomofpress/dangerzone/blob/7c4e62954f4ee71726de0a23655c8f791f05f290/dangerzone/isolation_provider/base.py#L90-L94).

I believe this is because the generator returned by `executor.map` is not consumed -  from [`ThreadPoolExecutor` docs](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.Executor.map):

> If a _fn_ call raises an exception, then that exception will be raised when its value is retrieved from the iterator.

Here is a simplified form showing the issue:

```python
>>> from concurrent.futures import ThreadPoolExecutor
>>>
>>> def do_work(i):
...     print(f"do_work({i})")
...     1 / 0
...
>>> with ThreadPoolExecutor(max_workers=4) as executor:
...     _ = executor.map(do_work, range(4))
...
do_work(0)
do_work(1)
do_work(2)
do_work(3)
>>>
```

**Comment by apyrgio** [comment]
Thanks a lot for bringing this issue to our attention, and for writing a test case.

I agree that the generator result should be consumed in principle, but we catch and log all exceptions (as you've already pointed out) [here](https://github.com/freedomofpress/dangerzone/blob/7c4e62954f4ee71726de0a23655c8f791f05f290/dangerzone/isolation_provider/base.py#L90-L94). I have to dig deeper, but my bet would be that there's a different underlying cause :-/.

**Comment by naglis** [comment]
> but we catch and log all exceptions (as you've already pointed out) [here](https://github.com/freedomofpress/dangerzone/blob/7c4e62954f4ee71726de0a23655c8f791f05f290/dangerzone/isolation_provider/base.py#L90-L94)

FWIW, I've ran into this in CLI tests when dummy conversion is used. The `Dummy` isolation provider overrides the [`convert` method](https://github.com/freedomofpress/dangerzone/blob/main/dangerzone/isolation_provider/dummy.py#L35-L70) and does not have any exception handling.

I do not have a test case when using e.g. the container isolation provider (which IIUC uses the `convert` method defined on the [base isolation provider](https://github.com/freedomofpress/dangerzone/blob/7c4e62954f4ee71726de0a23655c8f791f05f290/dangerzone/isolation_provider/base.py#L63-L94)), but the two sections ([here](https://github.com/freedomofpress/dangerzone/blob/7c4e62954f4ee71726de0a23655c8f791f05f290/dangerzone/isolation_provider/base.py#L69-L70) and [here](https://github.com/freedomofpress/dangerzone/blob/7c4e62954f4ee71726de0a23655c8f791f05f290/dangerzone/isolation_provider/base.py#L90-L94) (come to think of it, it also applies to the [`except errors.ConverterProcException`](https://github.com/freedomofpress/dangerzone/blob/main/dangerzone/isolation_provider/base.py#L83-L85) and [`except errors.ConversionException`](https://github.com/freedomofpress/dangerzone/blob/main/dangerzone/isolation_provider/base.py#L87-L88) blocks as well)) I've mentioned could hide exceptions if an exception were to occur inside them, since those sections are not inside a `try`/`except` ([this](https://github.com/freedomofpress/dangerzone/blob/7c4e62954f4ee71726de0a23655c8f791f05f290/dangerzone/isolation_provider/base.py#L90-L94) part is inside the `except Exception` block, but any potential exception coming from inside the `except` block is not handled (there is no exception handling in [`convert_doc`](https://github.com/freedomofpress/dangerzone/blob/7c4e62954f4ee71726de0a23655c8f791f05f290/dangerzone/logic.py#L75)) and would be swallowed by `exception.map`).

To simulate a swallowed exception when using the container provider, we would have to raise it explicitly. E.g. try adding `1 / 0` [here](https://github.com/freedomofpress/dangerzone/blob/7c4e62954f4ee71726de0a23655c8f791f05f290/dangerzone/isolation_provider/base.py#L70) (before the `try` block). Running `dev_scripts/dangerzone-cli /tmp/sample.pdf` then results in:
```
╭──────────────────────────╮
│           ▄██▄           │
│          ██████          │
│         ███▀▀▀██         │
│        ███   ████        │
│       ███   ██████       │
│      ███   ▀▀▀▀████      │
│     ███████  ▄██████     │
│    ███████ ▄█████████    │
│   ████████████████████   │
│    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀    │
│                          │
│    Dangerzone v0.6.0     │
│ https://dangerzone.rocks │
╰──────────────────────────╯
[INFO ] Assigning ID '0sHZEe' to doc '/tmp/sample.pdf'

Converting document to safe PDF
[DEBUG] Marking doc 0sHZEe as 'converting'
```

**Comment by apyrgio** [comment]
Got it. So we practically need a `try: ... except Exception: log.exception` at the top level, that would log any stray exceptions from the exception blocks you pointed out.

**Comment by naglis** [comment]
Indeed. IIUC this wrapping handler should also mark the document as failed upon exception (if it was not done already) to correctly [report it](https://github.com/freedomofpress/dangerzone/blob/94179a1d91a3adc993fdf9b32e7311901dade939/dangerzone/cli.py#L108-L111) at the end.

**Comment by amnak613** [comment]
I'm interested in contributing to this

**Comment by apyrgio** [comment]
Cool! Hopefully this issue provides enough context. In a nutshell, we want to:
1. Catch and report all stray conversion exceptions from [`IsolationProvider.convert`](https://github.com/freedomofpress/dangerzone/blob/c3a570eb7d81d42aa3974d1d91e2d0abfed966f2/dangerzone/isolation_provider/base.py#L68).
2. Mark the related document as failed.

**Comment by amnak613** [comment]
Setting up the environment might take a while because I'm busy right now

**Comment by amnak613** [comment]
Started looking into this issue

**Comment by almet** [comment]
@amnak613 don't hesitate to let me know if you need any help setting things up, or reviewing the changes.

**Comment by amnak613** [comment]
@almet thanks! I was able to set up the local env and am trying to recreate the issue thats occurring and was wondering if you knew how to run it locally? 

running this code 
`python3 dev_scripts/dangerzone-cli /tmp/sample.pdf` 

gives this error message

FileNotFoundError: [Errno 2] No such file or directory: '/tmp/sample.pdf'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/amnakhan/open-source/dangerzone/dangerzone/dangerzone/errors.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^

**Comment by almet** [comment]
This is the expected error message: it's because the `/tmp/sample.pdf` doesn't exist on your machine.

If your dev environment is setup, you should be able to run the tests with `make test`.

Once this is good on your end, the best way is to add new tests (and @naglis [provided some already](https://github.com/naglis/dangerzone/commit/0d214c14d3c9045b9eeb7764fdedb55df4d9a5a3#diff-4e8715c7a425ee52e74b7df4d34efd32e8c92f3e60bd51bc2e1ad5943b82032eR222)) and run them and see them fail.

When that's done, it'll be time to fix the code as specified by @apyrgio.
