### ISSUE TITLE
PySide6 no longer supports Python 3.8

### ISSUE THREAD

**Issue by apyrgio** [freedomofpress/dangerzone#780]
It has come to our attention that the latest PySide6 release (6.7.0) has [dropped](https://wiki.qt.io/Qt_for_Python_Development_Notes#29._February_2024) support for Python 3.8. Dangerzone still supports this Python version, since it is [still used](https://packages.ubuntu.com/focal/python3) by Ubuntu Focal.

In practice, this doesn't make a difference to our actual Ubuntu Focal users, since they use PySide2. However, this causes a problem for Windows and macOS users. The Python >= 3.8 restriction means that PySide6 is pinned to 6.6.3.1, instead of moving forward to 6.7.0. Since Windows/macOS users get PySide6 from PyPI, in the event of a PySide6 security issue, we will not be able to update it right away.

For reference, these are the EOL dates for Python 3.8 and Ubuntu Focal respectively:
* [Python 3.8](https://endoflife.date/python): October 31st, 2024
* [Ubuntu Focal](https://endoflife.date/ubuntu): April 2nd, 2025 (ESM ends in April 2nd, 2030)

**Comment by naglis** [comment]
I saw #618 which mentions that Ubuntu Focal has support for Python 3.9. Would that be an option?

**Comment by apyrgio** [comment]
Oh, very good observation! Yes, I think we could set the minimum Python3 version in our build instructions to >= 3.9 ([currently set](https://github.com/freedomofpress/dangerzone/blob/7c4e62954f4ee71726de0a23655c8f791f05f290/stdeb.cfg#L6) to 3.6 :bangbang:) . This way, the newer Python3 package will be downloaded. For `pyproject.toml`, we can similarly bump our lowest supported Python version to 3.9, and maybe add a little note in our `BUILD.md` file.

There's a minor catch here: what happens if there's an application in the user's Ubuntu Focal system that is not compatible with Python 3.9. In that case, there will be a package conflict. That's probably something we should check with `apt-cache rdepends [python3|python3.9]`.

**Comment by apyrgio** [comment]
This issue has been resolved by the following PRs:
* https://github.com/freedomofpress/dangerzone/pull/820
* https://github.com/freedomofpress/dangerzone/pull/818
