### ISSUE TITLE
Enable dependabot to learn about updates to GitHub Actions

### ISSUE THREAD

**Issue by apyrgio** [freedomofpress/dangerzone#782]
I would suggest enabling dependabot to automatically propose updates to GitHub Actions, see https://github.com/freedomofpress/securedrop-docs/commit/94e7d7175c9049f4805dcb8500913baad030e2f3 as an example.

_Originally posted by @legoktm in https://github.com/freedomofpress/dangerzone/issues/771#issuecomment-2045319384_

**Comment by iArchitSharma** [comment]
@apyrgio Can i work on this?

**Comment by apyrgio** [comment]
Sure, thanks for taking a look.
