### ISSUE TITLE
Dangerzone not opening on macOS after installation.

### ISSUE THREAD

**Issue by tenzyns** [freedomofpress/dangerzone#783]
I had docker desktop already installed when I installed Dangerzone. But It doesn't open ever after a system reboot. I'm on mac Monterery verstion 12.7.4

**Comment by apyrgio** [comment]
Hi! Really sorry for the late reply, but we're wrapping up things for 0.6.1, and it's a bit hectic. I'll need you to clarify a bit the "doesn't open" situation, if you have some time.

* Which Dangerzone version are you using?
* What happens when you run `/Applications/Dangerzone.app/Contents/MacOS/dangerzone`?
* Did you encounter any issue when installing the .dmg you downloaded from our website?

**Comment by tenzyns** [comment]
Hi, thanks for getting back.  I have Dangerzone version 0.6.0-i686. I didn't face any issue during the installation. 
I got this message after the command suggested. 
```
[2039] Error loading Python lib '/Applications/Dangerzone.app/Contents/Frameworks/libpython3.11.dylib': dlopen: dlopen(/Applications/Dangerzone.app/Contents/Frameworks/libpython3.11.dylib, 0x000A): Symbol not found: (_mkfifoat)
  Referenced from: '/Applications/Dangerzone.app/Contents/Frameworks/libpython3.11.dylib'
  Expected in: '/usr/lib/libSystem.B.dylib' 
```
my python version is 3.10.4

**Comment by apyrgio** [comment]
Perfect, that's one of the issues we'll be tackling in the upcoming hotfix release: https://github.com/freedomofpress/dangerzone/issues/471

We'll build the macOS .dmg with a different Python version, and our understanding is that this should fix this issue. The release will be out in 1-2 weeks I believe. Once it's out, I'll make sure to circle back here and ask you to test the new installer.

In the meantime, I wish I could give a workaround, but I'm not aware of one :-/

**Comment by apyrgio** [comment]
Dangerzone 0.6.1 [is out](https://github.com/freedomofpress/dangerzone/releases/tag/v0.6.1) :partying_face: . I would appreciate it if you could check that the new build solves your issue.

**Comment by apyrgio** [comment]
Another user has [reported](https://github.com/freedomofpress/dangerzone/issues/471#issuecomment-2109593845) that the original issue ("Symbol not found") has been resolved. I'm closing this issue, but if you still encounter this problem, we can reopen it.
