### ISSUE TITLE
AttributeError: module 'PySide2.QtGui' has no attribute 'QAction' when running on Qt5

### ISSUE THREAD

**Issue by naglis** [freedomofpress/dangerzone#788]
Reproduced on Arch Linux when running on Qt5 (Qt5/PySide2 version: 5.15.13 (system-wide)) starting Dangerzone both from source (https://github.com/freedomofpress/dangerzone/commit/8cdb2d572038cda19ab2c53b61abbfb9150fe6f5) and as an installed package (version 0.6.0).

If I am not mistaken, Qt5 is only used on Ubuntu Focal and update checks [are disabled by default](https://github.com/freedomofpress/dangerzone/blob/8cdb2d572038cda19ab2c53b61abbfb9150fe6f5/dangerzone/gui/updater.py#L165-L166) on Linux, so the probability of users running into it is rather low.

Steps to reproduce:

- In Dangerzone `settings.json` config file, set `updater_check` key to `true` to force update checks and set `updated_latest_version` key to a version that is higher than the currently installed/used Dangerzone version (e.g. `"0.7.0"`).
- Start Dangerzone GUI from command line (ensure that Qt5 is being used).
- Traceback is printed in the terminal:
  ```
  Traceback (most recent call last):
    File "/usr/lib/python3.11/site-packages/dangerzone/gui/main_window.py", line 291, in handle_updates
      success_action = QtGui.QAction("New version available", hamburger_menu)  # type: ignore [attr-defined]
                       ^^^^^^^^^^^^^
  AttributeError: module 'PySide2.QtGui' has no attribute 'QAction'
  ```
- Dangerzone window remains functional, the hamburger menu is displaying the `hamburger_menu_update_success.svg` icon, but the "New version available" menu entry is not displayed.

---

After a quick look at the documentation, it seems that in PySide2 `QAction` is available under [the `PySide2.QtWidgets` namespace](https://doc.qt.io/qtforpython-5/PySide2/QtWidgets/QAction.html#PySide2.QtWidgets.PySide2.QtWidgets.QAction), whereas in PySide6 it [resides under `PySide6.QtGui`](https://doc.qt.io/qtforpython-6/PySide6/QtGui/QAction.html).
IIUC there are two cases where `QAction` is used:

https://github.com/freedomofpress/dangerzone/blob/8cdb2d572038cda19ab2c53b61abbfb9150fe6f5/dangerzone/gui/main_window.py#L270
https://github.com/freedomofpress/dangerzone/blob/8cdb2d572038cda19ab2c53b61abbfb9150fe6f5/dangerzone/gui/main_window.py#L291

and the issue would manifest itself if update checking is enabled and there is a new version of there were errors when checking for updates.

A potential fix could be to [import `QAction` directly](https://github.com/freedomofpress/dangerzone/blob/8cdb2d572038cda19ab2c53b61abbfb9150fe6f5/dangerzone/gui/main_window.py#L15-L21) from the right module based on which Qt version is being used and the use the `QAction(...)` name directly.

**Comment by apyrgio** [comment]
Yet another nice dig :star_struck: . Indeed, almost none of our end-users are affected, since updates are disabled by default in Linux. Still, this issue does not affect Ubuntu Focal only. We use Pyside2 in every Debian-based distro, and PySide2 still relies on Qt5 (e.g., see [PySide2 dependencies](https://packages.debian.org/trixie/python3-pyside2.qtgui) on Debian Trixie).

Given that the gravity of the situation is kinda low, I'd not address it in this particular release. However, your fix makes sense, and we can add it in the next release.
