### ISSUE TITLE
Dangerzone is listed as a PDF viewer to open safe documents with on Linux

### ISSUE THREAD

**Issue by naglis** [freedomofpress/dangerzone#790]
Tested on Arch Linux/Ubuntu 22.04 when Dangerzone 0.6.0 is installed as a package. This [only applies](https://github.com/freedomofpress/dangerzone/blob/8cdb2d572038cda19ab2c53b61abbfb9150fe6f5/dangerzone/gui/logic.py#L99) to Linux systems.

![Screenshot of Dangerzone 0.6.0 running on Ubuntu 22.04 showing Dangerzone listed as an application to open safe PDF files after conversion](https://github.com/freedomofpress/dangerzone/assets/827324/152375f1-9dcc-4c4e-b307-7d95a0fd2280)

On Linux, Dangerzone allows to select a PDF viewer to use to open safe PDF documents after conversion. The list of available PDF viewers [is populated by parsing](https://github.com/freedomofpress/dangerzone/blob/8cdb2d572038cda19ab2c53b61abbfb9150fe6f5/dangerzone/gui/logic.py#L97) the .desktop entries of all available applications and returning ones that can open files with `application/pdf` mimetype. Currently, Dangerzone itself is included in this list (if Dangerzone is installed as a package system-wide), although in the code there is a [specific check](https://github.com/freedomofpress/dangerzone/blob/8cdb2d572038cda19ab2c53b61abbfb9150fe6f5/dangerzone/gui/logic.py#L114) to exclude Dangerzone from the list, however the check is done on the lowercase name `dangerzone` and the application name from the .desktop entry ([which is `Dangerzone`](https://github.com/freedomofpress/dangerzone/blob/8cdb2d572038cda19ab2c53b61abbfb9150fe6f5/install/linux/press.freedom.dangerzone.desktop#L2)) and so the condition never matches.

I believe it makes sense to exclude Dangerzone from the list of PDF viewers as Dangerzone cannot display PDFs (at least, not currently, see also #424) and repeatedly converting a safe document does not make much sense.

The trivial fix would be to use `Dangerzone` [as the application name in the check](https://github.com/freedomofpress/dangerzone/blob/8cdb2d572038cda19ab2c53b61abbfb9150fe6f5/dangerzone/gui/logic.py#L114), however, IIUC `pyxdg` [`DesktopEntry.getName()`](https://github.com/takluyver/pyxdg/blob/1d23e483ae869ee9532aca43b133cc43f63626a3/xdg/DesktopEntry.py#L67) [returns a localized name](https://github.com/takluyver/pyxdg/blob/1d23e483ae869ee9532aca43b133cc43f63626a3/xdg/DesktopEntry.py#L68) and if Dangerzone is translated in the future (#132), the `Name` key in the Dangerzone's .desktop file might differ in other languages. To avoid that, `DesktopEntry.get('Name', locale=False)` could be used to ignore localizations. Another option could be to use a different way to identify the Dangerzone application, e.g. the [name of the .desktop file](https://github.com/freedomofpress/dangerzone/blob/8cdb2d572038cda19ab2c53b61abbfb9150fe6f5/install/linux/press.freedom.dangerzone.desktop#L2) (`press.freedom.dangerzone`).

**Comment by apyrgio** [comment]
That's a very nice dig! I'd go with the trivial fix for now and not future-proofing the application, since a potential localization effort will radically rewrite the strings in any case. I'll include a better check in a PR I'll send soon.

**Comment by naglis** [comment]
> Damn. Great example of how [fixing a bug](https://github.com/freedomofpress/dangerzone/commit/3d426ed36bb373eee21f81d3df6c284b4d492431) created another one.

IIUC by refactoring [`_find_pdf_viewers`](https://github.com/freedomofpress/dangerzone/blob/8cdb2d572038cda19ab2c53b61abbfb9150fe6f5/dangerzone/gui/logic.py#L97) a bit (e.g. to allow controlling the search paths) we could write tests for it to check Dangerzone is excluded/some example application is found.
