### ISSUE TITLE
Docker is installed but isn't running on Ubuntu 22.04

### ISSUE THREAD

**Issue by fj-de-torres** [freedomofpress/dangerzone#792]
I installed Docker Desktop on Ubuntu 22.04 LTS following the instructions on the official website. But even when Docker is running (both in the foreground and in the background), I still get the message 'Docker is installed but isn't running'. So DangerZone doesn't seem to be able to detect that Docker is actually running and I can't use it.

**Comment by apyrgio** [comment]
Hm, in Ubuntu 22.04 you don't actually need Docker. You only need `podman`, which is installed as a dependency of Dangerzone. Probably an error message of ours threw you off, sorry for that.

Could you please run `dangerzone-cli <document>`, where `<document>` is the path of a document you want to convert, and write here the error you're seeing? I believe Podman is somehow misconfigured, and that's why Dangerzone shows this (bad) error message.

**Comment by fj-de-torres** [comment]
Hi! Thanks a lot for your quick response. The initial mistake was that I need to run it with root privileges but the menu access does it as my standard user. But when I run it with sudo, I get this error:
sudo dangerzone-cli Data\ Structures\ and\ Algorithms\ with\ Python\[Undergraduate\ Topics\ in\ Computer\ Science\(UTCS\)\]\[UTiCS\]\,\ Springer\,\ 2015\(it-ebooks\)\(A0\).pdf 
╭──────────────────────────╮
│           ▄██▄           │
│          ██████          │
│         ███▀▀▀██         │
│        ███   ████        │
│       ███   ██████       │
│      ███   ▀▀▀▀████      │
│     ███████  ▄██████     │
│    ███████ ▄█████████    │
│   ████████████████████   │
│    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀    │
│                          │
│    Dangerzone v0.6.0     │
│ https://dangerzone.rocks │
╰──────────────────────────╯
Assigning ID 'LRJ058' to doc '/home/francisco/Documents/Data Structures and Algorithms with Python[Undergraduate Topics in Computer Science(UTCS)][UTiCS], Springer, 2015(it-ebooks)(A0).pdf'

Converting document to safe PDF
> /usr/bin/podman run --network none -u dangerzone --log-driver none --security-opt no-new-privileges --userns keep-id --cap-drop all --rm -i dangerzone.rocks/dangerzone /usr/bin/python3 -m dangerzone.conversion.doc_to_pixels
[doc LRJ058] 0% Converting page 1/369 to pixels
[doc LRJ058] 0% Converting page 2/369 to pixels
[doc LRJ058] 0% Converting page 3/369 to pixels
[doc LRJ058] 0% Converting page 4/369 to pixels
[doc LRJ058] 0% Converting page 5/369 to pixels
[doc LRJ058] 0% Converting page 6/369 to pixels
[doc LRJ058] 0% Converting page 7/369 to pixels
[doc LRJ058] 0% Converting page 8/369 to pixels
[doc LRJ058] 1% Converting page 9/369 to pixels
[doc LRJ058] 1% Converting page 10/369 to pixels
[doc LRJ058] 1% Converting page 11/369 to pixels
[doc LRJ058] 1% Converting page 12/369 to pixels
[doc LRJ058] 1% Converting page 13/369 to pixels
[doc LRJ058] 1% Converting page 14/369 to pixels
[doc LRJ058] 1% Converting page 15/369 to pixels
[doc LRJ058] 1% Converting page 16/369 to pixels
[doc LRJ058] 2% Converting page 17/369 to pixels
[doc LRJ058] 2% Converting page 18/369 to pixels
[doc LRJ058] 2% Converting page 19/369 to pixels
[doc LRJ058] 2% Converting page 20/369 to pixels
[doc LRJ058] 2% Converting page 21/369 to pixels
[doc LRJ058] 2% Converting page 22/369 to pixels
[doc LRJ058] 2% Converting page 23/369 to pixels
[doc LRJ058] 3% Converting page 24/369 to pixels
[doc LRJ058] 3% Converting page 25/369 to pixels
[doc LRJ058] 3% Converting page 26/369 to pixels
[doc LRJ058] 3% Converting page 27/369 to pixels
[doc LRJ058] 3% Converting page 28/369 to pixels
[doc LRJ058] 3% Converting page 29/369 to pixels
[doc LRJ058] 3% Converting page 30/369 to pixels
[doc LRJ058] 3% Converting page 31/369 to pixels
[doc LRJ058] 4% Converting page 32/369 to pixels
[doc LRJ058] 4% Converting page 33/369 to pixels
[doc LRJ058] 4% Converting page 34/369 to pixels
[doc LRJ058] 4% Converting page 35/369 to pixels
[doc LRJ058] 4% Converting page 36/369 to pixels
[doc LRJ058] 4% Converting page 37/369 to pixels
[doc LRJ058] 4% Converting page 38/369 to pixels
[doc LRJ058] 5% Converting page 39/369 to pixels
[doc LRJ058] 5% Converting page 40/369 to pixels
[doc LRJ058] 5% Converting page 41/369 to pixels
[doc LRJ058] 5% Converting page 42/369 to pixels
[doc LRJ058] 5% Converting page 43/369 to pixels
[doc LRJ058] 5% Converting page 44/369 to pixels
[doc LRJ058] 5% Converting page 45/369 to pixels
[doc LRJ058] 5% Converting page 46/369 to pixels
[doc LRJ058] 6% Converting page 47/369 to pixels
[doc LRJ058] 6% Converting page 48/369 to pixels
[doc LRJ058] 6% Converting page 49/369 to pixels
[doc LRJ058] 6% Converting page 50/369 to pixels
[doc LRJ058] 6% Converting page 51/369 to pixels
[doc LRJ058] 6% Converting page 52/369 to pixels
[doc LRJ058] 6% Converting page 53/369 to pixels
[doc LRJ058] 7% Converting page 54/369 to pixels
[doc LRJ058] 7% Converting page 55/369 to pixels
[doc LRJ058] 7% Converting page 56/369 to pixels
[doc LRJ058] 7% Converting page 57/369 to pixels
[doc LRJ058] 7% Converting page 58/369 to pixels
[doc LRJ058] 7% Converting page 59/369 to pixels
[doc LRJ058] 7% Converting page 60/369 to pixels
[doc LRJ058] 7% Converting page 61/369 to pixels
[doc LRJ058] 8% Converting page 62/369 to pixels
[doc LRJ058] 8% Converting page 63/369 to pixels
[doc LRJ058] 8% Converting page 64/369 to pixels
[doc LRJ058] 8% Converting page 65/369 to pixels
[doc LRJ058] 8% Converting page 66/369 to pixels
[doc LRJ058] 8% Converting page 67/369 to pixels
[doc LRJ058] 8% Converting page 68/369 to pixels
[doc LRJ058] 9% Converting page 69/369 to pixels
[doc LRJ058] 9% Converting page 70/369 to pixels
[doc LRJ058] 9% Converting page 71/369 to pixels
[doc LRJ058] 9% Converting page 72/369 to pixels
[doc LRJ058] 9% Converting page 73/369 to pixels
[doc LRJ058] 9% Converting page 74/369 to pixels
[doc LRJ058] 9% Converting page 75/369 to pixels
[doc LRJ058] 9% Converting page 76/369 to pixels
[doc LRJ058] 10% Converting page 77/369 to pixels
[doc LRJ058] 10% Converting page 78/369 to pixels
[doc LRJ058] 10% Converting page 79/369 to pixels
[doc LRJ058] 10% Converting page 80/369 to pixels
[doc LRJ058] 10% Converting page 81/369 to pixels
[doc LRJ058] 10% Converting page 82/369 to pixels
[doc LRJ058] 10% Converting page 83/369 to pixels
[doc LRJ058] 11% Converting page 84/369 to pixels
[doc LRJ058] 11% Converting page 85/369 to pixels
[doc LRJ058] 11% Converting page 86/369 to pixels
[doc LRJ058] 11% Converting page 87/369 to pixels
[doc LRJ058] 11% Converting page 88/369 to pixels
[doc LRJ058] 11% Converting page 89/369 to pixels
[doc LRJ058] 11% Converting page 90/369 to pixels
[doc LRJ058] 11% Converting page 91/369 to pixels
[doc LRJ058] 12% Converting page 92/369 to pixels
[doc LRJ058] 12% Converting page 93/369 to pixels
[doc LRJ058] 12% Converting page 94/369 to pixels
[doc LRJ058] 12% Converting page 95/369 to pixels
[doc LRJ058] 12% Converting page 96/369 to pixels
[doc LRJ058] 12% Converting page 97/369 to pixels
[doc LRJ058] 12% Converting page 98/369 to pixels
[doc LRJ058] 13% Converting page 99/369 to pixels
[doc LRJ058] 13% Converting page 100/369 to pixels
[doc LRJ058] 13% Converting page 101/369 to pixels
[doc LRJ058] 13% Converting page 102/369 to pixels
[doc LRJ058] 13% Converting page 103/369 to pixels
[doc LRJ058] 13% Converting page 104/369 to pixels
[doc LRJ058] 13% Converting page 105/369 to pixels
[doc LRJ058] 13% Converting page 106/369 to pixels
[doc LRJ058] 14% Converting page 107/369 to pixels
[doc LRJ058] 14% Converting page 108/369 to pixels
[doc LRJ058] 14% Converting page 109/369 to pixels
[doc LRJ058] 14% Converting page 110/369 to pixels
[doc LRJ058] 14% Converting page 111/369 to pixels
[doc LRJ058] 14% Converting page 112/369 to pixels
[doc LRJ058] 14% Converting page 113/369 to pixels
[doc LRJ058] 15% Converting page 114/369 to pixels
[doc LRJ058] 15% Converting page 115/369 to pixels
[doc LRJ058] 15% Converting page 116/369 to pixels
[doc LRJ058] 15% Converting page 117/369 to pixels
[doc LRJ058] 15% Converting page 118/369 to pixels
[doc LRJ058] 15% Converting page 119/369 to pixels
[doc LRJ058] 15% Converting page 120/369 to pixels
[doc LRJ058] 15% Converting page 121/369 to pixels
[doc LRJ058] 16% Converting page 122/369 to pixels
[doc LRJ058] 16% Converting page 123/369 to pixels
[doc LRJ058] 16% Converting page 124/369 to pixels
[doc LRJ058] 16% Converting page 125/369 to pixels
[doc LRJ058] 16% Converting page 126/369 to pixels
[doc LRJ058] 16% Converting page 127/369 to pixels
[doc LRJ058] 16% Converting page 128/369 to pixels
[doc LRJ058] 16% Converting page 129/369 to pixels
[doc LRJ058] 17% Converting page 130/369 to pixels
[doc LRJ058] 17% Converting page 131/369 to pixels
[doc LRJ058] 17% Converting page 132/369 to pixels
[doc LRJ058] 17% Converting page 133/369 to pixels
[doc LRJ058] 17% Converting page 134/369 to pixels
[doc LRJ058] 17% Converting page 135/369 to pixels
[doc LRJ058] 17% Converting page 136/369 to pixels
[doc LRJ058] 18% Converting page 137/369 to pixels
[doc LRJ058] 18% Converting page 138/369 to pixels
[doc LRJ058] 18% Converting page 139/369 to pixels
[doc LRJ058] 18% Converting page 140/369 to pixels
[doc LRJ058] 18% Converting page 141/369 to pixels
[doc LRJ058] 18% Converting page 142/369 to pixels
[doc LRJ058] 18% Converting page 143/369 to pixels
[doc LRJ058] 18% Converting page 144/369 to pixels
[doc LRJ058] 19% Converting page 145/369 to pixels
[doc LRJ058] 19% Converting page 146/369 to pixels
[doc LRJ058] 19% Converting page 147/369 to pixels
[doc LRJ058] 19% Converting page 148/369 to pixels
[doc LRJ058] 19% Converting page 149/369 to pixels
[doc LRJ058] 19% Converting page 150/369 to pixels
[doc LRJ058] 19% Converting page 151/369 to pixels
[doc LRJ058] 20% Converting page 152/369 to pixels
[doc LRJ058] 20% Converting page 153/369 to pixels
[doc LRJ058] 20% Converting page 154/369 to pixels
[doc LRJ058] 20% Converting page 155/369 to pixels
[doc LRJ058] 20% Converting page 156/369 to pixels
[doc LRJ058] 20% Converting page 157/369 to pixels
[doc LRJ058] 20% Converting page 158/369 to pixels
[doc LRJ058] 20% Converting page 159/369 to pixels
[doc LRJ058] 21% Converting page 160/369 to pixels
[doc LRJ058] 21% Converting page 161/369 to pixels
[doc LRJ058] 21% Converting page 162/369 to pixels
[doc LRJ058] 21% Converting page 163/369 to pixels
[doc LRJ058] 21% Converting page 164/369 to pixels
[doc LRJ058] 21% Converting page 165/369 to pixels
[doc LRJ058] 21% Converting page 166/369 to pixels
[doc LRJ058] 22% Converting page 167/369 to pixels
[doc LRJ058] 22% Converting page 168/369 to pixels
[doc LRJ058] 22% Converting page 169/369 to pixels
[doc LRJ058] 22% Converting page 170/369 to pixels
[doc LRJ058] 22% Converting page 171/369 to pixels
[doc LRJ058] 22% Converting page 172/369 to pixels
[doc LRJ058] 22% Converting page 173/369 to pixels
[doc LRJ058] 22% Converting page 174/369 to pixels
[doc LRJ058] 23% Converting page 175/369 to pixels
[doc LRJ058] 23% Converting page 176/369 to pixels
[doc LRJ058] 23% Converting page 177/369 to pixels
[doc LRJ058] 23% Converting page 178/369 to pixels
[doc LRJ058] 23% Converting page 179/369 to pixels
[doc LRJ058] 23% Converting page 180/369 to pixels
[doc LRJ058] 23% Converting page 181/369 to pixels
[doc LRJ058] 24% Converting page 182/369 to pixels
[doc LRJ058] 24% Converting page 183/369 to pixels
[doc LRJ058] 24% Converting page 184/369 to pixels
[doc LRJ058] 24% Converting page 185/369 to pixels
[doc LRJ058] 24% Converting page 186/369 to pixels
[doc LRJ058] 24% Converting page 187/369 to pixels
[doc LRJ058] 24% Converting page 188/369 to pixels
[doc LRJ058] 24% Converting page 189/369 to pixels
[doc LRJ058] 25% Converting page 190/369 to pixels
[doc LRJ058] 25% Converting page 191/369 to pixels
[doc LRJ058] 25% Converting page 192/369 to pixels
[doc LRJ058] 25% Converting page 193/369 to pixels
[doc LRJ058] 25% Converting page 194/369 to pixels
[doc LRJ058] 25% Converting page 195/369 to pixels
[doc LRJ058] 25% Converting page 196/369 to pixels
[doc LRJ058] 26% Converting page 197/369 to pixels
[doc LRJ058] 26% Converting page 198/369 to pixels
[doc LRJ058] 26% Converting page 199/369 to pixels
[doc LRJ058] 26% Converting page 200/369 to pixels
[doc LRJ058] 26% Converting page 201/369 to pixels
[doc LRJ058] 26% Converting page 202/369 to pixels
[doc LRJ058] 26% Converting page 203/369 to pixels
[doc LRJ058] 26% Converting page 204/369 to pixels
[doc LRJ058] 27% Converting page 205/369 to pixels
[doc LRJ058] 27% Converting page 206/369 to pixels
[doc LRJ058] 27% Converting page 207/369 to pixels
[doc LRJ058] 27% Converting page 208/369 to pixels
[doc LRJ058] 27% Converting page 209/369 to pixels
[doc LRJ058] 27% Converting page 210/369 to pixels
[doc LRJ058] 27% Converting page 211/369 to pixels
[doc LRJ058] 28% Converting page 212/369 to pixels
[doc LRJ058] 28% Converting page 213/369 to pixels
[doc LRJ058] 28% Converting page 214/369 to pixels
[doc LRJ058] 28% Converting page 215/369 to pixels
[doc LRJ058] 28% Converting page 216/369 to pixels
[doc LRJ058] 28% Converting page 217/369 to pixels
[doc LRJ058] 28% Converting page 218/369 to pixels
[doc LRJ058] 28% Converting page 219/369 to pixels
[doc LRJ058] 29% Converting page 220/369 to pixels
[doc LRJ058] 29% Converting page 221/369 to pixels
[doc LRJ058] 29% Converting page 222/369 to pixels
[doc LRJ058] 29% Converting page 223/369 to pixels
[doc LRJ058] 29% Converting page 224/369 to pixels
[doc LRJ058] 29% Converting page 225/369 to pixels
[doc LRJ058] 29% Converting page 226/369 to pixels
[doc LRJ058] 30% Converting page 227/369 to pixels
[doc LRJ058] 30% Converting page 228/369 to pixels
[doc LRJ058] 30% Converting page 229/369 to pixels
[doc LRJ058] 30% Converting page 230/369 to pixels
[doc LRJ058] 30% Converting page 231/369 to pixels
[doc LRJ058] 30% Converting page 232/369 to pixels
[doc LRJ058] 30% Converting page 233/369 to pixels
[doc LRJ058] 30% Converting page 234/369 to pixels
[doc LRJ058] 31% Converting page 235/369 to pixels
[doc LRJ058] 31% Converting page 236/369 to pixels
[doc LRJ058] 31% Converting page 237/369 to pixels
[doc LRJ058] 31% Converting page 238/369 to pixels
[doc LRJ058] 31% Converting page 239/369 to pixels
[doc LRJ058] 31% Converting page 240/369 to pixels
[doc LRJ058] 31% Converting page 241/369 to pixels
[doc LRJ058] 32% Converting page 242/369 to pixels
[doc LRJ058] 32% Converting page 243/369 to pixels
[doc LRJ058] 32% Converting page 244/369 to pixels
[doc LRJ058] 32% Converting page 245/369 to pixels
[doc LRJ058] 32% Converting page 246/369 to pixels
[doc LRJ058] 32% Converting page 247/369 to pixels
[doc LRJ058] 32% Converting page 248/369 to pixels
[doc LRJ058] 32% Converting page 249/369 to pixels
[doc LRJ058] 33% Converting page 250/369 to pixels
[doc LRJ058] 33% Converting page 251/369 to pixels
[doc LRJ058] 33% Converting page 252/369 to pixels
[doc LRJ058] 33% Converting page 253/369 to pixels
[doc LRJ058] 33% Converting page 254/369 to pixels
[doc LRJ058] 33% Converting page 255/369 to pixels
[doc LRJ058] 33% Converting page 256/369 to pixels
[doc LRJ058] 33% Converting page 257/369 to pixels
[doc LRJ058] 34% Converting page 258/369 to pixels
[doc LRJ058] 34% Converting page 259/369 to pixels
[doc LRJ058] 34% Converting page 260/369 to pixels
[doc LRJ058] 34% Converting page 261/369 to pixels
[doc LRJ058] 34% Converting page 262/369 to pixels
[doc LRJ058] 34% Converting page 263/369 to pixels
[doc LRJ058] 34% Converting page 264/369 to pixels
[doc LRJ058] 35% Converting page 265/369 to pixels
[doc LRJ058] 35% Converting page 266/369 to pixels
[doc LRJ058] 35% Converting page 267/369 to pixels
[doc LRJ058] 35% Converting page 268/369 to pixels
[doc LRJ058] 35% Converting page 269/369 to pixels
[doc LRJ058] 35% Converting page 270/369 to pixels
[doc LRJ058] 35% Converting page 271/369 to pixels
[doc LRJ058] 35% Converting page 272/369 to pixels
[doc LRJ058] 36% Converting page 273/369 to pixels
[doc LRJ058] 36% Converting page 274/369 to pixels
[doc LRJ058] 36% Converting page 275/369 to pixels
[doc LRJ058] 36% Converting page 276/369 to pixels
[doc LRJ058] 36% Converting page 277/369 to pixels
[doc LRJ058] 36% Converting page 278/369 to pixels
[doc LRJ058] 36% Converting page 279/369 to pixels
[doc LRJ058] 37% Converting page 280/369 to pixels
[doc LRJ058] 37% Converting page 281/369 to pixels
[doc LRJ058] 37% Converting page 282/369 to pixels
[doc LRJ058] 37% Converting page 283/369 to pixels
[doc LRJ058] 37% Converting page 284/369 to pixels
[doc LRJ058] 37% Converting page 285/369 to pixels
[doc LRJ058] 37% Converting page 286/369 to pixels
[doc LRJ058] 37% Converting page 287/369 to pixels
[doc LRJ058] 38% Converting page 288/369 to pixels
[doc LRJ058] 38% Converting page 289/369 to pixels
[doc LRJ058] 38% Converting page 290/369 to pixels
[doc LRJ058] 38% Converting page 291/369 to pixels
[doc LRJ058] 38% Converting page 292/369 to pixels
[doc LRJ058] 38% Converting page 293/369 to pixels
[doc LRJ058] 38% Converting page 294/369 to pixels
[doc LRJ058] 39% Converting page 295/369 to pixels
[doc LRJ058] 39% Converting page 296/369 to pixels
[doc LRJ058] 39% Converting page 297/369 to pixels
[doc LRJ058] 39% Converting page 298/369 to pixels
[doc LRJ058] 39% Converting page 299/369 to pixels
[doc LRJ058] 39% Converting page 300/369 to pixels
[doc LRJ058] 39% Converting page 301/369 to pixels
[doc LRJ058] 39% Converting page 302/369 to pixels
[doc LRJ058] 40% Converting page 303/369 to pixels
[doc LRJ058] 40% Converting page 304/369 to pixels
[doc LRJ058] 40% Converting page 305/369 to pixels
[doc LRJ058] 40% Converting page 306/369 to pixels
[doc LRJ058] 40% Converting page 307/369 to pixels
[doc LRJ058] 40% Converting page 308/369 to pixels
[doc LRJ058] 40% Converting page 309/369 to pixels
[doc LRJ058] 41% Converting page 310/369 to pixels
[doc LRJ058] 41% Converting page 311/369 to pixels
[doc LRJ058] 41% Converting page 312/369 to pixels
[doc LRJ058] 41% Converting page 313/369 to pixels
[doc LRJ058] 41% Converting page 314/369 to pixels
[doc LRJ058] 41% Converting page 315/369 to pixels
[doc LRJ058] 41% Converting page 316/369 to pixels
[doc LRJ058] 41% Converting page 317/369 to pixels
[doc LRJ058] 42% Converting page 318/369 to pixels
[doc LRJ058] 42% Converting page 319/369 to pixels
[doc LRJ058] 42% Converting page 320/369 to pixels
[doc LRJ058] 42% Converting page 321/369 to pixels
[doc LRJ058] 42% Converting page 322/369 to pixels
[doc LRJ058] 42% Converting page 323/369 to pixels
[doc LRJ058] 42% Converting page 324/369 to pixels
[doc LRJ058] 43% Converting page 325/369 to pixels
[doc LRJ058] 43% Converting page 326/369 to pixels
[doc LRJ058] 43% Converting page 327/369 to pixels
[doc LRJ058] 43% Converting page 328/369 to pixels
[doc LRJ058] 43% Converting page 329/369 to pixels
[doc LRJ058] 43% Converting page 330/369 to pixels
[doc LRJ058] 43% Converting page 331/369 to pixels
[doc LRJ058] 43% Converting page 332/369 to pixels
[doc LRJ058] 44% Converting page 333/369 to pixels
[doc LRJ058] 44% Converting page 334/369 to pixels
[doc LRJ058] 44% Converting page 335/369 to pixels
[doc LRJ058] 44% Converting page 336/369 to pixels
[doc LRJ058] 44% Converting page 337/369 to pixels
[doc LRJ058] 44% Converting page 338/369 to pixels
[doc LRJ058] 44% Converting page 339/369 to pixels
[doc LRJ058] 45% Converting page 340/369 to pixels
[doc LRJ058] 45% Converting page 341/369 to pixels
[doc LRJ058] 45% Converting page 342/369 to pixels
[doc LRJ058] 45% Converting page 343/369 to pixels
[doc LRJ058] 45% Converting page 344/369 to pixels
[doc LRJ058] 45% Converting page 345/369 to pixels
[doc LRJ058] 45% Converting page 346/369 to pixels
[doc LRJ058] 45% Converting page 347/369 to pixels
[doc LRJ058] 46% Converting page 348/369 to pixels
[doc LRJ058] 46% Converting page 349/369 to pixels
[doc LRJ058] 46% Converting page 350/369 to pixels
[doc LRJ058] 46% Converting page 351/369 to pixels
[doc LRJ058] 46% Converting page 352/369 to pixels
[doc LRJ058] 46% Converting page 353/369 to pixels
[doc LRJ058] 46% Converting page 354/369 to pixels
[doc LRJ058] 47% Converting page 355/369 to pixels
[doc LRJ058] 47% Converting page 356/369 to pixels
[doc LRJ058] 47% Converting page 357/369 to pixels
[doc LRJ058] 47% Converting page 358/369 to pixels
[doc LRJ058] 47% Converting page 359/369 to pixels
[doc LRJ058] 47% Converting page 360/369 to pixels
[doc LRJ058] 47% Converting page 361/369 to pixels
[doc LRJ058] 47% Converting page 362/369 to pixels
[doc LRJ058] 48% Converting page 363/369 to pixels
[doc LRJ058] 48% Converting page 364/369 to pixels
[doc LRJ058] 48% Converting page 365/369 to pixels
[doc LRJ058] 48% Converting page 366/369 to pixels
[doc LRJ058] 48% Converting page 367/369 to pixels
[doc LRJ058] 48% Converting page 368/369 to pixels
[doc LRJ058] 48% Converting page 369/369 to pixels
[doc LRJ058] 49% Converted document to pixels
> /usr/bin/podman run --network none -u dangerzone --log-driver none --security-opt no-new-privileges --userns keep-id --cap-drop all --rm -i -v /tmp/tmpoe7z0q8_:/safezone:Z -e OCR=0 -e OCR_LANGUAGE=None dangerzone.rocks/dangerzone /usr/bin/python3 -m dangerzone.conversion.pixels_to_pdf
ERROR pixels-to-pdf failed
ERROR [doc LRJ058] 0% Unknown error code '1'

Failed to convert document(s)
/home/francisco/Documents/Data Structures and Algorithms with Python[Undergraduate Topics in Computer Science(UTCS)][UTiCS], Springer, 2015(it-ebooks)(A0).pdf
Something similar happens on Windows

**Comment by apyrgio** [comment]
> The initial mistake was that I need to run it with root privileges but the menu access does it as my standard user. 

Actually, that's not a mistake! It's best to run Dangerzone as a non-root user, as most GUI applications. Could you perhaps run it instead as your regular user and post the logs here?

Also, let's check for some common reasons for failures:
1. Is your user ID `1000`? You can check with `id`. The reason I'm asking is due to #624.
2. Does `podman info` return any error?
3. What's the result of:

   ```
   /usr/bin/podman run --network none -u dangerzone --log-driver none --security-opt no-new-privileges --userns keep-id --cap-drop all --rm -i dangerzone.rocks/dangerzone echo "Works!"
   ```

**Comment by fj-de-torres** [comment]
Hello Sir!
Yes, my id is 1000. Is the first user created on my system. I need to run dangerzone and podman with root privileges since my regular user (id = 1000) doesn't have writing permissions on those folders (where podman tries to create a container for dangerzone or the code you provided). So, the result for what you suggested is:
`Error: error creating tmpdir: mkdir /run/user/1001: permission denied
`
The result when I try to use dangerzone-cli as a regular user (id = 1000):
`dangerzone-cli TESTS.pdf 
╭──────────────────────────╮
│           ▄██▄           │
│          ██████          │
│         ███▀▀▀██         │
│        ███   ████        │
│       ███   ██████       │
│      ███   ▀▀▀▀████      │
│     ███████  ▄██████     │
│    ███████ ▄█████████    │
│   ████████████████████   │
│    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀    │
│                          │
│    Dangerzone v0.6.1     │
│ https://dangerzone.rocks │
╰──────────────────────────╯
Assigning ID 'HtetrJ' to doc '/home/francisco/Documents/TESTS.pdf'
Error: error creating tmpdir: mkdir /run/user/1001: permission denied
Traceback (most recent call last):
  File "/usr/bin/dangerzone-cli", line 33, in <module>
    sys.exit(load_entry_point('dangerzone==0.6.1', 'console_scripts', 'dangerzone-cli')())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/dangerzone/errors.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/dangerzone/cli.py", line 89, in cli_main
    dangerzone.isolation_provider.install()
  File "/usr/lib/python3/dist-packages/dangerzone/isolation_provider/container.py", line 59, in install
    if Container.is_container_installed():
  File "/usr/lib/python3/dist-packages/dangerzone/isolation_provider/container.py", line 101, in is_container_installed
    found_image_id = subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/podman', 'image', 'list', '--format', '{{.ID}}', 'dangerzone.rocks/dangerzone']' returned non-zero exit status 125.
`
When doing the same with sudo (last lines of log):

`[doc ITK3uE] 48% Converting page 731/733 to pixels
[doc ITK3uE] 48% Converting page 732/733 to pixels
[doc ITK3uE] 48% Converting page 733/733 to pixels
[doc ITK3uE] 49% Converted document to pixels
> /usr/bin/podman run --network none -u dangerzone --log-driver none --security-opt no-new-privileges --userns keep-id --cap-drop all --rm -i --name dangerzone-pixels-to-pdf-ITK3uE -v /tmp/tmp0t1xs2ju:/safezone:Z -e OCR=0 -e OCR_LANGUAGE=None dangerzone.rocks/dangerzone /usr/bin/python3 -m dangerzone.conversion.pixels_to_pdf
ERROR pixels-to-pdf failed
ERROR [doc ITK3uE] 0% Unknown error code '1'

Failed to convert document(s)
/home/francisco/Documents/TESTS.pdf
`

**Comment by apyrgio** [comment]
_(I edited the above code blocks in your comment for clarity. When pasting code, prefer to use Markdown's triple ticks (<code>```</code>)_

> Yes, my id is 1000. Is the first user created on my system. I need to run dangerzone and podman with root privileges since my regular user (id = 1000) doesn't have writing permissions on those folders (where podman tries to create a container for dangerzone or the code you provided). So, the result for what you suggested is:
> `Error: error creating tmpdir: mkdir /run/user/1001: permission denied`

And yet, Podman attempts to create a temporary directory for a different user (`1001`). This rings a bell (https://github.com/freedomofpress/dangerzone/issues/620#issuecomment-1815011494).

Let's dig deeper. Can you write down the output of the following commands?

```
id
env | grep -e 'TEMP\|TMP'
podman info
```

As for running Dangerzone as root, it's a use case that's unfortunately not supported (and to be frank, it would be best avoided). You _may_ make it work, but our best bet is actually fixing your Podman installation, so that you can run Dangerzone as your regular user.

**Comment by fj-de-torres** [comment]
```
id
```
#Result: uid=1000(francisco) gid=1000(francisco) groups=1000(francisco),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),122(lpadmin),135(lxd),136(sambashare),141(vboxusers)
for
```
env | grep -e 'TEMP\|TMP'
```
#Result: nothing at all.
for
```
podman info
```
#Result: Error: error creating tmpdir: mkdir /run/user/1001: permission denied

Thanks a lot for your help :)

**Comment by apyrgio** [comment]
Cool, thanks for the output. Can I ask you to share one more?

```
env | grep XDG_RUNTIME_DIR
```

**Comment by fj-de-torres** [comment]
Sure! Here it is:
```
XDG_RUNTIME_DIR=/run/user/1000
``

**Comment by apyrgio** [comment]
Sigh, I'm out of ideas. It seems to me as an issue with your Podman installation. The fact that `podman info` cannot even run, or that it refers to `/run/user/1001` is a sign that something is wrong there.

Searching for this issue on the internet, I found a [similar report](https://www.reddit.com/r/podman/comments/x1mmz3/rhel8_podman4112_cannot_run_because_it_tries_to/). If you have recently switched your home directory, then Podman probably has kept some state there. In that case, it's best to nuke the Podman configuration.

**Comment by fj-de-torres** [comment]
**It works!**
I followed your last instructions: to nuke the podman's installation. I just didn't know how to until I found this post: [https://github.com/containers/podman/issues/5049](https://github.com/containers/podman/issues/5049). Specifically this little action:
```
rf ~/.local/share/containers/
```
Thanks a lot for your help and for this great software :)

**Comment by apyrgio** [comment]
Oh, that's great! I'm happy that you got it resolved. I'll close this issue now, but feel free to create a new one, if you stumble onto something else.
