### ISSUE TITLE
Dangerzone not opening in Windows 10

### ISSUE THREAD

**Issue by CypherLeon** [freedomofpress/dangerzone#81]
hi i am using windows 10 i downloaded the Dangerzone, after clean installation when tried to open shown as"Failed to execute script Dangerzone" seen please help

**Comment by connect192168** [comment]
+1
Running Windows 10 Version 1909
Upon first run, the script prompts for the install of docker for windows. This is sucessful.
Docker prompts for a restart. This was executed.
Upon restart, I manually ran the docker to confirm that there was no post-restart configuration needed. None was shown to be needed, so I closed dockerforwin and ran the dangerzone script.
Upon running the dangerzone script, this popup window is launched:
![image](https://user-images.githubusercontent.com/38689351/82533441-2dae6100-9b3b-11ea-91fe-a6ec212764d5.png)

**Comment by KaceCM** [comment]
Hello, same problem i can't open dangerzone

**Comment by MetalSpace** [comment]
Hi, Same problem. Is the bug will be fixed ?

**Comment by deeplow** [comment]
Thanks everyone for opening this issue and sorry for the late response. It's been two years now. Hopefully this is no longer a problem. From our testing it works on windows.
