### ISSUE TITLE
QA and Release version 0.7.0

### ISSUE THREAD

**Issue by almet** [freedomofpress/dangerzone#839]
## Pre-release

Before making a release, all of these should be complete:

- [x] Copy the entirety of these instructions onto a new issue and call it **QA and Release version \<VERSION\>**
- [x] [Add new Linux platforms and remove obsolete ones](#add-new-platforms-and-remove-obsolete-ones)
- [x] Bump the Python dependencies using `poetry lock`
- [x] [Check for official PySide6 versions](#check-for-official-pyside6-versions)
- [x] Update `version` in `pyproject.toml`
- [x] Update `share/version.txt`
- [x] Update the "Version" field in `install/linux/dangerzone.spec`
- [x] Update screenshot in `README.md`, if necessary
- [x] CHANGELOG.md should be updated to include a list of all major changes since the last release
- [x] Create a PGP-signed git tag for the version, e.g., for dangerzone `v0.1.0`:

## QA

- [x] Make sure that the tip of the `main` branch passes the CI tests.
- [x] Make sure that the Apple account has a valid application password and has
      agreed to the latest Apple terms (see [macOS release](#macos-release)
      section).
- [x] Create a test build in Windows and make sure it works:
  - [x] Check if the suggested Python version is still supported.
  - [x] Create a new development environment with Poetry.
  - [x] Build the container image and ensure the development environment uses
    the new image.
  - [x] Run the Dangerzone tests.
  - [x] Build and run the Dangerzone .exe
  - [x] Test some QA scenarios (see [Scenarios](#Scenarios) below).
- [x] Create a test build in macOS (Intel CPU) and make sure it works:
  - [x] Check if the suggested Python version is still supported.
  - [x] Create a new development environment with Poetry.
  - [x] Build the container image and ensure the development environment uses
    the new image.
  - [x] Run the Dangerzone tests.
  - [x] Create and run an app bundle.
  - [x] Test some QA scenarios (see [Scenarios](#Scenarios) below).
- [x] Create a test build in macOS (M1/2 CPU) and make sure it works:
  - [x] Check if the suggested Python version is still supported.
  - [x] Create a new development environment with Poetry.
  - [x] Build the container image and ensure the development environment uses
    the new image.
  - [x] Run the Dangerzone tests.
  - [x] Create and run an app bundle.
  - [x] Test some QA scenarios (see [Scenarios](#Scenarios) below).
- [x] Create a test build in the most recent Ubuntu LTS platform (Ubuntu 24.04
  as of writing this) and make sure it works:
  - [x] Create a new development environment with Poetry.
  - [x] Build the container image and ensure the development environment uses
    the new image.
  - [x] Run the Dangerzone tests.
  - [x] Create a .deb package and install it system-wide.
  - [x] Test some QA scenarios (see [Scenarios](#Scenarios) below).
- [x] Create a test build in the most recent Fedora platform (Fedora 40 as of
  writing this) and make sure it works:
  - [x] Create a new development environment with Poetry.
  - [x] Build the container image and ensure the development environment uses
    the new image.
  - [x] Run the Dangerzone tests.
  - [x] Create an .rpm package and install it system-wide.
  - [x] Test some QA scenarios (see [Scenarios](#Scenarios)).
- [x] Create a test build in the most recent Qubes Fedora template (Fedora 39 as
  of writing this) and make sure it works:
  - [x] Create a new development environment with Poetry.
  - [x] Run the Dangerzone tests.
  - [x] Create a Qubes .rpm package and install it system-wide.
  - [x] Ensure that the Dangerzone application appears in the "Applications"
    tab.
  - [x] Test some QA scenarios (see [Scenarios](#Scenarios) below) and make sure
    they spawn disposable qubes.

### macOS Release

- [x] Verify and install the latest supported Python version from [python.org](https://www.python.org/downloads/macos/)
- [x] Verify and checkout the git tag for this release
- [x] Run `poetry install`
- [x] Run `poetry run ./install/macos/build-app.py`; this will make `dist/Dangerzone.app`
- [x] Run `poetry run ./install/macos/build-app.py --only-codesign`; this will make `dist/Dangerzone.dmg`
- [x] Notarize it: `xcrun notarytool submit --apple-id "<email>" --keychain-profile "dz-notarytool-release-key" dist/Dangerzone.dmg`
- [x] Wait for it to get approved, check status with: `xcrun notarytool info <REQUEST_UUID> --apple-id "<email>" --keychain-profile "dz-notarytool-release-key"`
- [x] After it's approved, staple the ticket: `xcrun stapler staple dist/Dangerzone.dmg`
- [x] Rename `Dangerzone.dmg` to `Dangerzone-$VERSION.dmg`.

#### Releasing and Signing

- [x] Verify and checkout the git tag for this release
- [x] Run `poetry install`
- [x] Copy the container image into the VM
- [x] Run `poetry run .\install\windows\build-app.bat`
- [x] When you're done you will have `dist\Dangerzone.msi`
- [x] Rename `Dangerzone.msi` to `Dangerzone-$VERSION.msi`.

#### Debian/Ubuntu

For each supported debian and ubuntu version:

- [x] Build the latest container
- [x] Create a .deb file
- [x] Publish the .deb under `./deb_dist` to the
[`freedomofpress/apt-tools-prod`](https://github.com/freedomofpress/apt-tools-prod)
repo, by sending a PR. Follow the instructions in that repo on how to do so.

#### Fedora

For each supported fedora version:

- [x] Build the latest container
- [x] Create a .rpm file
- [x] Publish the .deb under `./deb_dist` to the
[`freedomofpress/yum-tools-prod`](https://github.com/freedomofpress/yum-tools-prod)
repo, by sending a PR. Follow the instructions in that repo on how to do so.

#### Qubes

- [x] Create a .rpm for Qubes

and similarly publish it to the [`freedomofpress/yum-tools-prod`](https://github.com/freedomofpress/yum-tools-prod)
repo.

## Publishing the Release

To publish the release:

- [x] Create an archive of the Dangerzone source in `tar.gz` format
- [x] Run container scan on the produced container images (some time may have passed since the artifacts were built)
- [x] Collect the assets in a single directory, calculate their SHA-256 hashes, and sign them.
- [x] Create a new **draft** release on GitHub and upload the macOS and Windows installers.
- [x] Upload the `container.tar.gz` i686 image that was created in the previous step
- [x] Upload the detached signatures (.asc) and checksum file.
- [x] Update the [Dangerzone website](https://github.com/freedomofpress/dangerzone.rocks) to link to the new installers and signatures
- [x] Update the brew cask release of Dangerzone with a [PR like this one](https://github.com/Homebrew/homebrew-cask/pull/116319)
- [x] Update version and download links in `README.md`

## Post-release

- [x] Toot release announcement on our mastodon account @dangerzone@fosstodon.org
- [x] Extend the `check_repos.yml` CI test for the newly added platforms

**Comment by apyrgio** [comment]
Woo hoo, we have a 0.7.0 release issue! I see that you copy-pasted everything, but I think it's better if we just copy the checklists. See the previous release issues as well on what we keep.
