### ISSUE TITLE
Install PyMuPDF via the prebuilt Python wheels for musl

### ISSUE THREAD

**Issue by apyrgio** [freedomofpress/dangerzone#850]
Starting from PyMuPDF 1.24.6, the developers have [added](https://github.com/pymupdf/PyMuPDF/releases/tag/1.24.6) support for prebuilt musl-based wheels:

> Add musllinux x86_64 wheels to release.

This change can significantly improve our Dockerfile, and specifically these two lines:

https://github.com/freedomofpress/dangerzone/blob/e7e3430ca11ef768485b2d27e069ea76e9923fec/Dockerfile#L10-L11

Instead of installing build tools (`g++`, `make`, etc.) and building PyMuPDF from source, `pip install` will install the necessary wheels. This will greatly improve the build times of our container image.

There's one problem though: There is still no support for prebuilt musl-based wheels for aarch64 architectures. Since our Dockerfile is the same between our two architectures, we can't easily do different actions per architecture. For example, the pre-built wheels also create the following path: `/usr/lib/python3.12/site-packages/PyMuPDFb.libs/`. The regular wheels do not include this path, and therefore our Dockerfile would have to conditionally copy it, depending on the architecture:

https://github.com/freedomofpress/dangerzone/blob/e7e3430ca11ef768485b2d27e069ea76e9923fec/Dockerfile#L64-L65

This is still an open problem, and we have to wait until the PyMuPDF devs have a solution for it.

**Comment by apyrgio** [comment]
The PyMuPDF devs still don't offer aarch64 musl-based wheels on 1.24.9: https://pypi.org/project/PyMuPDFb/1.24.9/#files. We can't pin PyMuPDF indefinitely, so we must make progress on this front. I have already sent a PR (#851), and we can make the following changes to accommodate for aarch64 wheels:

1. Update our `pymupdf-build` container image to unconditionally create an empty directory `/usr/lib/python3.12/site-packages/PyMuPDFb.libs` dir. This way, we can unconditionally copy it to our final container image, even in the case of ARM environments.
2. Keep our PyMuPDF build dependencies in our `pymupdf-build` image. This way, we will be able to build PyMuPDF in the case of ARM environments.
3. Conditionally remove the `pymupdfb` requirements in the `build-image.py` script, only in the case of ARM environments.

With the above changes, we will be able to utilize the musl-based wheels in x86_64 architectures, and build a PyMuPDF wheel from source in ARM architectures.

**Comment by almet** [comment]
> With the above changes, we will be able to utilize the musl-based wheels in x86_64 architectures, and build a PyMuPDF wheel from source in ARM architectures.

This has been done in https://github.com/freedomofpress/dangerzone/pull/902. I'm closing this issue and opening a new one about specific PyMuPDF wheel support for musl on aarch64.
