### ISSUE TITLE
[Feature Request] Kali Linux support is it possible to support it for the apt 3rd party repository ?

### ISSUE THREAD

**Issue by AkechiShiro** [freedomofpress/dangerzone#857]
Hi,

I would like to feature request the support for Kali Linux please as Kali Linux is based on Debian I think it's not too far to have the support.

**Comment by almet** [comment]
Hi,

As you mention, we are releasing Debian and Ubuntu packages, which targets:

- Ubuntu 24.04 (noble)
- Ubuntu 23.10 (mantic)
- Ubuntu 22.04 (jammy)
- Ubuntu 20.04 (focal)
- Debian 13 (trixie)
- Debian 12 (bookworm)
- Debian 11 (bullseye)
  
Under the hood, they're currently using the same `.deb` package, which could potentially work for you as well for Kali Linux. You can try downloading the latest `.deb` from the [apt-tools-prod](https://github.com/freedomofpress/apt-tools-prod/tree/main/dangerzone/bookworm) repository and give it a go.

But, bear in mind it is not one of the supported platforms right now, so, [here be dragons](https://en.wikipedia.org/wiki/Here_be_dragons).

Good luck :crossed_fingers:

**Comment by AkechiShiro** [comment]
Thanks, I followed the build instruction to be on the safer side, I'll try this out next time ! Should I close this issue as not planned ?
