### ISSUE TITLE
not starting, "not enough values to unpack"

### ISSUE THREAD

**Issue by boredsquirrel** [freedomofpress/dangerzone#899]
I use Fedora Kinoite 40, using rpm-ostree. I added the .repo file and installed dangerzone, rebooted and it shows up fine in the GUI and in the terminal.

But it doesnt launch, also not when opening a PDF with it.

```
~ ❯❯❯ dangerzone
[DEBUG] Inferred system color scheme as OSColorMode.DARK
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/xdg/IniFile.py", line 78, in parse
    key, value = line.split("=", 1)
    ^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/dangerzone", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/dangerzone/errors.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/dangerzone/gui/__init__.py", line 147, in gui_main
    dangerzone = DangerzoneGui(app, isolation_provider=container)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/dangerzone/gui/logic.py", line 56, in __init__
    self.pdf_viewers = self._find_pdf_viewers()
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/dangerzone/gui/logic.py", line 126, in _find_pdf_viewers
    desktop_entry = DesktopEntry(full_filename)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/xdg/DesktopEntry.py", line 34, in __init__
    self.parse(filename)
  File "/usr/lib/python3.12/site-packages/xdg/DesktopEntry.py", line 48, in parse
    IniFile.parse(self, file, ["Desktop Entry", "KDE Desktop Entry"])
  File "/usr/lib/python3.12/site-packages/xdg/IniFile.py", line 80, in parse
    raise ParsingError("Invalid line: " + line, filename)
xdg.Exceptions.ParsingError: ParsingError in file '/var/home/user/.local/share/applications/SOMERANDOMDESKTOPENTRY.desktop', Invalid line: SOME LINE.' ;\
```

I have no idea why it would open a desktop entry in there and give an error? This was totally unrelated to dangerzone, a different app.

Operating System: Fedora Linux 40
KDE Plasma Version: 6.1.4
KDE Frameworks Version: 6.5.0
Qt Version: 6.7.2
Kernel Version: 6.10.4-200.fc40.x86_64 (64-bit)
Graphics Platform: Wayland

Python 3.12.4

the install added following packages:

```
Added:
  dangerzone-0.7.0-2.fc40.x86_64
  python3-appdirs-1.4.4-13.fc40.noarch
  python3-colorama-0.4.6-7.fc40.noarch
  python3-markdown-3.5.2-1.fc40.noarch
  python3-pyside6-6.7.2-3.fc40.x86_64
  python3-shiboken6-6.7.2-3.fc40.x86_64
  qt6-qt3d-6.7.2-1.fc40.x86_64
  qt6-qtcharts-6.7.2-1.fc40.x86_64
  qt6-qtconnectivity-6.7.2-1.fc40.x86_64
  qt6-qtdatavis3d-6.7.2-1.fc40.x86_64
  qt6-qtgraphs-6.7.2-1.fc40.x86_64
  qt6-qthttpserver-6.7.2-1.fc40.x86_64
  qt6-qtimageformats-6.7.2-1.fc40.x86_64
  qt6-qtlocation-6.7.2-1.fc40.x86_64
  qt6-qtnetworkauth-6.7.2-1.fc40.x86_64
  qt6-qtremoteobjects-6.7.2-1.fc40.x86_64
  qt6-qtscxml-6.7.2-1.fc40.x86_64
  qt6-qtserialbus-6.7.2-1.fc40.x86_64
  qt6-qttools-libs-help-6.7.2-1.fc40.x86_64
```

**Comment by apyrgio** [comment]
Thanks for the report @boredsquirrel. Indeed, it seems that if the `xdg` library encounters a malformed desktop entry, Dangerzone will fail. I'll make sure to track this for our 0.8.0 release and catch this exception.

In the meantime, the workaround I can offer is to move this desktop entry to another location. Hopefully it won't be much of an issue, since it's not XDG-compliant anyways.

**Comment by boredsquirrel** [comment]
thanks for the reply!

I just dont get why dangerzone, an app for opening files, would scan all my XDG desktop entries and fail if a random other entry is broken

**Comment by almet** [comment]
Once the PDFs have been converted, it's possible for dangerzone to open them using the default PDF handler, and to know which ones are available, it's iterating trough the desktop entries.

Hope it makes more sense :-)

Also worth nothing: we might also defer when we iterate over these files, as it's not a necessity when starting the application.

**Comment by boredsquirrel** [comment]
strange, isnt this normally done via a portal? Like, the modern way? I am sure there is an oldschool way, which this seems to be.

**Comment by almet** [comment]
> isnt this normally done via a portal? Like, the modern way?

Thanks for your comment :+1: 

You are correct, we are not using portals at the moment. In this specific case, it seems [we would be out of luck](https://github.com/flatpak/xdg-desktop-portal/issues/809) for getting the list of applications.

My understanding is that portals seem mainly useful when using Flatpak (or other desktop containerization frameworks). You seem to say that it is not only the case, and that we should rely on them here even if we are not inside Flatpak. Am I reading this correctly?

If that's the case, that would be great to have some more context on why this is, so we can consider making a change if we believe it's worth it :-)

**Comment by rocodes** [comment]
Sorry @boredsquirrel @almet, think I introduced this in #832 with not accounting for malformed .desktop files. Thanks for the find+the fix.
