### ISSUE TITLE
Dangerzone - cannot use it on Linux Mint 20 (docker)

### ISSUE THREAD

**Issue by broccolli-linux** [freedomofpress/dangerzone#90]
After following the installation steps, without errors, Dangerzone displays the following two messages:

**"Dangerzone requires Docker.
Docker should be instaslled, but it looks like it's not running in the background.
Click Ok to try starting the docker service. You will have to type your login password."**

[I click Ok and type my password]

**"Restarting docker appeared to work, but the service still isn't responding, quitting"**

I quickly checked I have docker installed by running `which docker`.

Some output from running `inxi -Fxz`
Distro: Linux Mint 20 Ulyana Cinnamon 64-bit
Kernel: 5.4.0-48-generic x86_64
base: Ubuntu 20.04 focal

**Comment by deeplow** [comment]
At the moment Dangerzone depends on podman and not on Linux. So this should not be an issue anymore. If this still happens, please feel free to re-open it.
