### ISSUE TITLE
Use github issue templates

### ISSUE THREAD

**Issue by almet** [freedomofpress/dangerzone#920]
Using github issue templates could help us have more context about the user environment, when they open a new issue. We could ask them for the following:

For bugs:

- OS name ? (Windows, MacOS, Linux)
- OS version? (explain how to get this information)
- Dangerzone version
- If on windows or MacOS:
	- Which Docker Desktop version?
- If on Linux:
	- Which Podman version?
	
What are the steps to help reproduce this bug?

**Comment by apyrgio** [comment]
I agree, and we could even ask them to run `dangerzone-cli` on each OS version, since it has a few more messages. Let's have something ready by the end of the release. I added it as a stretch goal for 0.8.0. Even the issue template is not super complete, it's more than nothing.
