### ISSUE TITLE
unspecified error converting .odt on Fedora Kinoite 

### ISSUE THREAD

**Issue by secretmango** [freedomofpress/dangerzone#934]
I am trying to convert a regular Libreoffice .odt file

Fedora Kinoite 40

podman version 5.2.3

Latest Libreoffice Flatpak

Dangerzone 0.7.0

```
[INFO] Container image installed
[INFO] Assigning ID 'ZZ5W74' to doc '/var/home/user/Downloads/some-file.odt'
[DEBUG] Removing all documents
[DEBUG] Marking doc ZZ5W74 as 'converting'
[INFO] > /usr/bin/podman run --log-driver none --security-opt no-new-privileges --cap-drop all --cap-add SYS_CHROOT --security-opt label=type:container_engine_t --network=none -u dangerzone --rm -i --name dangerzone-doc-to-pixels-ZZ5W74 --userns nomap dangerzone.rocks/dangerzone /usr/bin/python3 -m dangerzone.conversion.doc_to_pixels
[ERROR] [doc ZZ5W74] 0% Unspecified error
[DEBUG] Marking doc ZZ5W74 as 'failed'
```

afterwards the UI also doesnt allow to retry so I need to close the app and try again.

the same happens when disabling OCR.

I attach a test document where this happens.
[test-doc.odt](https://github.com/user-attachments/files/17195627/test-doc.odt)

**Comment by apyrgio** [comment]
Thanks for the test document. I can sanitize it in a regular Fedora 40 installation, so most likely there's an issue in your environment. Let's take a look, can you run some commands and paste the output here?

Info about your Podman instance:

```
podman info
podman version
podman images
```

Test if the Dangerzone container can start:

```
/usr/bin/podman run -e RUNSC_DEBUG=1 --log-driver none --security-opt no-new-privileges --cap-drop all --cap-add SYS_CHROOT --security-opt label=type:container_engine_t --network=none -u dangerzone --rm -i --userns nomap dangerzone.rocks/dangerzone /usr/bin/python3 -m dangerzone.conversion.doc_to_pixels
```
