### ISSUE TITLE
Docker Desktop running on Windows 10 Pro but Dangerzone says it's not

### ISSUE THREAD

**Issue by Decker-Mage** [freedomofpress/dangerzone#94]
When I open Dangerzone it reports that Docker Desktop is not running and offers to show it in Explorer. Loading it that way only opens the existing Docker Desktop that is running from system boot as I'm also running at least one other container or more.

**Comment by micahflee** [comment]
I believe this bug was fixed in Dangerzone 0.1.4, which was just released 3 days ago. Can you confirm you're using the latest version? https://github.com/firstlookmedia/dangerzone/releases/tag/v0.1.4

**Comment by JayBrown** [comment]
Same (or similar) issue on macOS. Dangerzone v0.1.4 with Docker running, but Dangerzone doesn't recognize that it's running, and wants to download Docker anyway, and crashes when you cancel the download.

fyi: Docker installed in `~/Developer/Applications`

**Comment by StephenGenusa** [comment]
I had the same problem. This was with a fresh install of Dangerzone and a first time install of Docker Desktop on Windows 10 Pro. 

The default install path for docker.exe is not 
"C:\\Program Files\\Docker\\Docker\\resources\\docker.exe" as defined in container.py but 
"C:\\Program Files\\Docker\\Docker\\resources\\bin\\docker.exe". 

From an admin CMD prompt I copied docker.exe into the container.py defined location and Dangerzone does run (although I get a warning from Docker Desktop about sharing a Windows file into a WSL 2 container "which may perform poorly" and a pdfseparate timeout in 60 seconds)

**Comment by Decker-Mage** [comment]
I should have used Everything to check each path. Thanks!

**Comment by deeplow** [comment]
This should be fixed now as the location of docker on windows is no longer hardcoded (as [it was before](https://github.com/freedomofpress/dangerzone/commit/3105a2c22928f38eb37f54001b850944739ffabc#diff-c71b3544ff6d4565f66adbb800868b57681888dd909b190a94227a41500c9db3L12-R12)) but instead is obtained [dynamically](https://github.com/freedomofpress/dangerzone/commit/d125a5004bd81d155928f10510aaa50b5e59a289).

So I'll close this for now, but if it still happens on the latest Dangerzone release, feel free to re-open it @Decker-Mage,
